// src/lib/materials/materials-catalog.ts
/**
 * Catálogo tipado maestro de materiales, insumos, herramientas y laboratorios virtuales.
 * SIGPDA-EMS · Ciclo Escolar 2026-2027
 * Fuente de verdad de los 244 slugs de los lotes P1-P6 (53 P1 ejecutados + 191 P2-P6)
 * de `matriz_materiales_v1/v2/v3/v4.md` y sus prompt-sets.
 */

export type MaterialCategory =
  | 'medicion'
  | 'laboratorio_quimica'
  | 'laboratorio_bio'
  | 'fisica'
  | 'herramientas'
  | 'computo'
  | 'seguridad_epp'
  | 'arte'
  | 'deportivo'
  | 'agro'
  | 'virtual'
  // Ampliación P2-P6 (2026-10-07): dominios de FFEO, FFE Laboral y Carreras BT
  | 'matematicas'
  | 'ofimatica'
  | 'alimentos'
  | 'salud'
  | 'construccion'
  | 'industrial'
  | 'logistica'
  | 'servicios'
  | 'energia';

export interface MaterialCatalogItem {
  slug: string;
  name: string;
  category: MaterialCategory;
  priority: 'P1' | 'P2';
  altText: string;
  aliases?: string[];
  eppRequerido?: string[];
  equivalenteVirtual?: {
    nombre: string;
    url: string;
    offline: boolean;
  };
}

export const MATERIALES_CATALOG: readonly MaterialCatalogItem[] = [
  // ── Instrumentación y Medición Eléctrica/Física ──────────────────────────
  {
    slug: 'multimetro',
    name: 'Multímetro Digital Autorango',
    category: 'medicion',
    priority: 'P1',
    altText: 'Multímetro digital con puntas de prueba y selector de magnitudes eléctricas',
    aliases: ['multímetro', 'polímetro', 'tester-digital'],
    eppRequerido: ['Gafas de seguridad', 'Calzado dieléctrico'],
    equivalenteVirtual: {
      nombre: 'Simulador Falstad CircuitJS',
      url: 'https://www.falstad.com/circuit/',
      offline: true,
    },
  },
  {
    slug: 'osciloscopio',
    name: 'Osciloscopio Digital de 2 Canales',
    category: 'medicion',
    priority: 'P1',
    altText: 'Osciloscopio digital de dos canales para análisis de formas de onda',
    aliases: ['osciloscopio-digital', 'pantalla-ondas'],
    eppRequerido: ['Gafas de seguridad'],
    equivalenteVirtual: {
      nombre: 'Simulador EveryCircuit / Falstad',
      url: 'https://www.falstad.com/circuit/',
      offline: true,
    },
  },
  {
    slug: 'fuente-poder',
    name: 'Fuente de Alimentación Regulable DC',
    category: 'medicion',
    priority: 'P1',
    altText: 'Fuente de poder regulada de 0 a 30V DC con limitador de corriente',
    aliases: ['fuente-dc', 'fuente-regulable'],
    eppRequerido: ['Gafas de seguridad'],
    equivalenteVirtual: {
      nombre: 'Tinkercad Circuits Fuente DC',
      url: 'https://www.tinkercad.com/circuits',
      offline: false,
    },
  },
  {
    slug: 'generador-funciones',
    name: 'Generador de Funciones y Señales',
    category: 'medicion',
    priority: 'P1',
    altText: 'Generador de señales senoidales, cuadradas y triangulares',
    aliases: ['generador-senales', 'generador-ondas'],
    eppRequerido: ['Gafas de seguridad'],
    equivalenteVirtual: {
      nombre: 'Falstad Function Generator',
      url: 'https://www.falstad.com/circuit/',
      offline: true,
    },
  },

  // ── Laboratorio de Ciencias, Química y Biología ──────────────────────────
  {
    slug: 'microscopio-optico',
    name: 'Microscopio Óptico Compuesto',
    category: 'laboratorio_bio',
    priority: 'P1',
    altText: 'Microscopio óptico binocular de laboratorio con revólver de 4 objetivos',
    aliases: ['microscopio', 'microscopio-binocular'],
    eppRequerido: ['Bata de laboratorio 100% algodón', 'Gafas de seguridad'],
    equivalenteVirtual: {
      nombre: 'Virtual Microscope NCBioNetwork',
      url: 'https://www.ncbionetwork.org/educational-resources/elearning/interactive-tools/virtual-microscope',
      offline: false,
    },
  },
  {
    slug: 'probeta',
    name: 'Probeta Graduada de Vidrio (100 ml)',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Probeta de vidrio borosilicato graduada de 100 ml con base hexagonal',
    aliases: ['cilindro-graduado'],
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
    equivalenteVirtual: {
      nombre: 'PhET Simulación de Densidad y Volumen',
      url: 'https://phet.colorado.edu/es/simulations/density',
      offline: true,
    },
  },
  {
    slug: 'probeta-graduada',
    name: 'Probeta Graduada de Vidrio',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Probeta de vidrio con escala graduada milimétrica y base ancha para medir volúmenes',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'matraz-erlenmeyer',
    name: 'Matraz Erlenmeyer de 250 ml',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Matraz Erlenmeyer de cuello estrecho para titulación y mezclas',
    aliases: ['erlenmeyer', 'matraz'],
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
    equivalenteVirtual: {
      nombre: 'PhET Concentración y Soluciones Químicas',
      url: 'https://phet.colorado.edu/es/simulations/concentration',
      offline: true,
    },
  },
  {
    slug: 'bureta',
    name: 'Bureta Graduada con Llave de Teflón (50 ml)',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Bureta de precisión de 50 ml para valoración ácido-base',
    aliases: ['bureta-quimica', 'bureta-50ml'],
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
    equivalenteVirtual: {
      nombre: 'Simulador de Titulación Ácido-Base',
      url: 'https://phet.colorado.edu/es/simulations/ph-scale',
      offline: true,
    },
  },
  {
    slug: 'balanza-digital',
    name: 'Balanza Digital de Precisión (0.01 g)',
    category: 'medicion',
    priority: 'P1',
    altText: 'Balanza digital electrónica para pesaje analítico en laboratorio',
    aliases: ['balanza-precision', 'bascula-digital'],
    equivalenteVirtual: {
      nombre: 'PhET Balanza y Masas',
      url: 'https://phet.colorado.edu/es/simulations/balancing-act',
      offline: true,
    },
  },
  {
    slug: 'phmetro',
    name: 'Medidor de pH Digital (pHímetro de Bolsillo)',
    category: 'medicion',
    priority: 'P1',
    altText: 'Potenciómetro medidor de pH con electrodo sumergible',
    aliases: ['medidor-ph', 'potenciometro-ph'],
    eppRequerido: ['Gafas de seguridad', 'Guantes de nitrilo'],
    equivalenteVirtual: {
      nombre: 'PhET Escala de pH Interactiva',
      url: 'https://phet.colorado.edu/es/simulations/ph-scale',
      offline: true,
    },
  },
  {
    slug: 'termometro',
    name: 'Termómetro de Laboratorio (-10°C a 110°C)',
    category: 'medicion',
    priority: 'P1',
    altText: 'Termómetro de inmersión total con escala graduada en grados Celsius',
    aliases: ['termometro-laboratorio', 'termometro-vidrio'],
    eppRequerido: ['Gafas de seguridad'],
    equivalenteVirtual: {
      nombre: 'PhET Estados de la Materia y Temperatura',
      url: 'https://phet.colorado.edu/es/simulations/states-of-matter',
      offline: true,
    },
  },
  {
    slug: 'cronometro',
    name: 'Cronómetro Digital con Memoria',
    category: 'medicion',
    priority: 'P1',
    altText: 'Cronómetro digital manual para registro de tiempos de cinemática',
    aliases: ['cronometro-digital', 'timer'],
    equivalenteVirtual: {
      nombre: 'Tracker Video Analysis & Chronometer',
      url: 'https://physlets.org/tracker/',
      offline: true,
    },
  },
  {
    slug: 'mechero-lab',
    name: 'Mechero Bunsen / Lámpara de Alcohol',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Mechero de laboratorio para calentamiento y esterilización térmica',
    aliases: ['mechero-bunsen', 'lampara-alcohol'],
    eppRequerido: ['Bata de laboratorio 100% algodón', 'Gafas de seguridad', 'Cabello recogido'],
    equivalenteVirtual: {
      nombre: 'PhET Cambios Térmicos y Calorimetría',
      url: 'https://phet.colorado.edu/es/simulations/energy-forms-and-changes',
      offline: true,
    },
  },
  {
    slug: 'embudo-de-vidrio',
    name: 'Embudo de Vidrio de Laboratorio',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Embudo de vidrio borosilicato con cono y tallo para filtración de sólidos',
    aliases: ['embudo-filtracion', 'embudo-lab'],
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
  },
  {
    slug: 'mortero-con-pilon',
    name: 'Mortero de Porcelana con Pilón',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Mortero de porcelana con pilón para trituración y pulverización de sólidos',
    aliases: ['mortero-porcelana', 'pilon-mortero'],
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'soporte-universal',
    name: 'Soporte Universal de Laboratorio',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Base pesada con varilla recta y pinzas para sujetar equipos y recipientes',
    aliases: ['soporte-lab', 'pinza-universal'],
    eppRequerido: ['Gafas de seguridad'],
  },

  // ── Física, Óptica y Magnetismo ──────────────────────────────────────────
  {
    slug: 'imanes',
    name: 'Juego de Imanes Didácticos (Barra y Herradura)',
    category: 'fisica',
    priority: 'P1',
    altText: 'Imanes de neodimio y alnico con polos Norte y Sur señalizados',
    aliases: ['juego-imanes', 'iman-barra'],
    equivalenteVirtual: {
      nombre: 'PhET Imán y Brújula de Faraday',
      url: 'https://phet.colorado.edu/es/simulations/faraday',
      offline: true,
    },
  },
  {
    slug: 'lentes-opticos',
    name: 'Juego de Lentes Ópticos Convergentes y Divergentes',
    category: 'fisica',
    priority: 'P1',
    altText: 'Set de lentes esféricos y prismas para demostración de refracción de luz',
    aliases: ['lentes-geometricos', 'prismas-opticos'],
    equivalenteVirtual: {
      nombre: 'PhET Óptica Geométrica',
      url: 'https://phet.colorado.edu/es/simulations/geometric-optics',
      offline: true,
    },
  },

  // ── Matemáticas y Pensamiento Matemático ─────────────────────────────────
  {
    slug: 'geoplano',
    name: 'Geoplano Didáctico con Bandas Elásticas',
    category: 'arte',
    priority: 'P1',
    altText: 'Geoplano cuadrado y circular para modelación geométrica plana',
    aliases: ['geoplano-cuadrado', 'tablero-geometrico'],
    equivalenteVirtual: {
      nombre: 'Polypad Geoboard (Mathigon)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'compas',
    name: 'Compás de Precisión Metálico',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Compás con adaptador para trazo de circunferencias y arcos',
    aliases: ['compas-dibujo', 'compas-precision'],
    equivalenteVirtual: {
      nombre: 'GeoGebra Geometría Web',
      url: 'https://www.geogebra.org/geometry',
      offline: true,
    },
  },
  {
    slug: 'dados',
    name: 'Juego de Dados Poliédricos y Estándar',
    category: 'medicion',
    priority: 'P1',
    altText: 'Dados de 6, 10 y 20 caras para experimentos de probabilidad y estadística',
    aliases: ['dados-probabilidad', 'dados-poliedricos'],
    equivalenteVirtual: {
      nombre: 'PhET Simulación de Probabilidad',
      url: 'https://phet.colorado.edu/es/simulations/plinko-probability',
      offline: true,
    },
  },
  {
    slug: 'regla-calculo',
    name: 'Regla de Cálculo y Escalas Numéricas',
    category: 'medicion',
    priority: 'P1',
    altText: 'Regla graduada en centímetros y pulgadas con escalas de conversión',
    aliases: ['regla-graduada', 'escalimetro'],
    equivalenteVirtual: {
      nombre: 'Desmos Calculadora Gráfica',
      url: 'https://www.desmos.com/calculator',
      offline: true,
    },
  },

  // ── Cómputo, TIC y Redes ─────────────────────────────────────────────────
  {
    slug: 'pc-escritorio',
    name: 'Computadora de Escritorio / Laptop',
    category: 'computo',
    priority: 'P1',
    altText: 'Equipo de cómputo con monitor, teclado y acceso a entorno de programación',
    aliases: ['computadora', 'laptop', 'pc'],
    equivalenteVirtual: {
      nombre: 'Google Colab / VS Code for Web',
      url: 'https://vscode.dev/',
      offline: true,
    },
  },
  {
    slug: 'impresora',
    name: 'Impresora Multifuncional de Inyección / Láser',
    category: 'computo',
    priority: 'P1',
    altText: 'Impresora para material didáctico, oficios y rúbricas impresas',
    aliases: ['impresora-laser', 'impresora-tinta'],
  },
  {
    slug: 'escaner',
    name: 'Escáner Digitalizador de Documentos',
    category: 'computo',
    priority: 'P1',
    altText: 'Escáner óptico para digitalización de evidencias y proyectos escolares',
    aliases: ['escaner-optico', 'digitalizador'],
  },
  {
    slug: 'multifuncional',
    name: 'Equipo Multifuncional de Oficina (Impresora/Copia/Escáner)',
    category: 'computo',
    priority: 'P1',
    altText: 'Equipo multifuncional para administración escolar y expedientes',
    aliases: ['fotocopiadora', 'copiadora-oficina'],
  },
  {
    slug: 'cable-red',
    name: 'Cable de Red Ethernet UTP Cat 6 con Conectores RJ45',
    category: 'computo',
    priority: 'P1',
    altText: 'Cable de par trenzado UTP con conectores RJ-45 para redes LAN',
    aliases: ['cable-ethernet', 'cable-utp'],
    equivalenteVirtual: {
      nombre: 'Cisco Packet Tracer',
      url: 'https://www.netacad.com/courses/packet-tracer',
      offline: true,
    },
  },
  {
    slug: 'crimpadora-red',
    name: 'Pinza Ponchadora / Crimpadora RJ45 y Pelacables',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Herramienta de crimpado para armado de cables de telecomunicaciones',
    aliases: ['ponchadora-rj45', 'crimpadora'],
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'tester-cable',
    name: 'Probador de Cables de Red (Tester RJ45 / RJ11)',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Probador de continuidad y mapeo de pines para redes Ethernet',
    aliases: ['probador-red', 'tester-lan'],
  },
  {
    slug: 'desarmadores-precision',
    name: 'Juego de Destornilladores de Precisión para Electrónica',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Set de desarmadores planos, Phillips y Torx para mantenimiento de equipos',
    aliases: ['destornilladores-precision', 'kit-desarmadores'],
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'arduino-kit',
    name: 'Kit de Robótica y Microcontrolador Arduino Uno',
    category: 'computo',
    priority: 'P1',
    altText: 'Placa de microcontrolador con protoboard, sensores y cables jumper',
    aliases: ['arduino-uno', 'kit-robotica'],
    equivalenteVirtual: {
      nombre: 'Tinkercad Circuits Arduino Simulator',
      url: 'https://www.tinkercad.com/circuits',
      offline: false,
    },
  },
  {
    slug: 'impresora-3d',
    name: 'Impresora 3D de Filamento (FDM)',
    category: 'computo',
    priority: 'P1',
    altText: 'Impresora 3D para prototipado rápido de piezas y modelos de ciencias',
    aliases: ['impresion-3d', 'fabricador-digital'],
    eppRequerido: ['Gafas de seguridad', 'Ventilación adecuada'],
    equivalenteVirtual: {
      nombre: 'Tinkercad 3D Design / UltiMaker Cura',
      url: 'https://www.tinkercad.com/',
      offline: true,
    },
  },

  // ── Herramientas de Taller, Electricidad y Domótica ───────────────────────
  {
    slug: 'destornilladores',
    name: 'Juego de Destornilladores con Mango Aislado',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Destornilladores planos y de cruz con aislamiento dieléctrico de 1000V',
    aliases: ['desarmadores', 'destornilladores-aislados'],
    eppRequerido: ['Gafas de seguridad', 'Guantes dieléctricos'],
  },
  {
    slug: 'alicates',
    name: 'Pinzas de Electricista / Alicates Universales',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Pinzas universales de corte y empalme para conductores eléctricos',
    aliases: ['pinzas-electricista', 'alicates-universales'],
    eppRequerido: ['Gafas de seguridad', 'Guantes mecánicos'],
  },
  {
    slug: 'contactos-electricos',
    name: 'Placas de Contactos Eléctricos, Apagadores y Clavijas',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Material de instalación eléctrica residencial para tableros de práctica',
    aliases: ['tomacorrientes', 'placas-apagador'],
    eppRequerido: ['Gafas de seguridad', 'Desenergización obligatoria'],
    equivalenteVirtual: {
      nombre: 'Simulador de Instalaciones Eléctricas Tinkercad',
      url: 'https://www.tinkercad.com/circuits',
      offline: false,
    },
  },
  {
    slug: 'perfocel',
    name: 'Tablero Perforado (Perfocel) para Montaje Eléctrico',
    category: 'herramientas',
    priority: 'P1',
    altText: 'Tablero de perfocel con bastidor para montaje de circuitos y domótica',
    aliases: ['tablero-practicas', 'panel-perfocel'],
    eppRequerido: ['Gafas de seguridad'],
  },

  // ── Agropecuario, Huerto y Medio Ambiente ────────────────────────────────
  {
    slug: 'huerto-semillero',
    name: 'Semillero y Charolas de Germinación Agroecológica',
    category: 'agro',
    priority: 'P1',
    altText: 'Charolas alveoladas de germinación para semillas de hortalizas',
    aliases: ['charola-germinacion', 'semillero-hortalizas'],
    eppRequerido: ['Guantes de jardinería'],
  },
  {
    slug: 'herramienta-jardin',
    name: 'Kit de Herramientas de Jardinería y Cultivo (Palas, Rastrillo)',
    category: 'agro',
    priority: 'P1',
    altText: 'Juego de herramientas manuales de labranza y trasplante para huertos',
    aliases: ['pala-jardineria', 'rastrillo-manual'],
    eppRequerido: ['Guantes de jardinería', 'Calzado cerrado'],
  },

  // ── Alimentos, Repostería y Nutrición ────────────────────────────────────
  {
    slug: 'horno-reposteria',
    name: 'Horno de Convección / Estufa de Cocina',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Horno con control de temperatura para panificación y conservación',
    aliases: ['horno-cocina', 'estufa-alimentos'],
    eppRequerido: ['Mandil de cocina', 'Guantes térmicos', 'Cofia'],
  },
  {
    slug: 'batidora',
    name: 'Batidora de Pedestal / Manual de Alimentos',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Batidora eléctrica para preparación de masas y emulsiones',
    aliases: ['batidora-electrica', 'mezcladora-alimentos'],
    eppRequerido: ['Cofia', 'Mandil'],
  },
  {
    slug: 'tabla-cortar',
    name: 'Tabla de Picar de Polietileno Grado Alimenticio',
    category: 'laboratorio_quimica',
    priority: 'P1',
    altText: 'Tabla higiénica de polietileno para corte seguro de materias primas',
    aliases: ['tabla-picar', 'tabla-polietileno'],
    eppRequerido: ['Mandil', 'Guantes higiénicos'],
  },

  // ── Dibujo Técnico y Diseño Gráfico ──────────────────────────────────────
  {
    slug: 'mesa-dibujo',
    name: 'Tablero de Dibujo Técnico y Regla T',
    category: 'arte',
    priority: 'P1',
    altText: 'Restirador portátil con regla paralela para trazo arquitectónico y vistas',
    aliases: ['tablero-dibujo', 'restirador-dibujo'],
    equivalenteVirtual: {
      nombre: 'LibreCAD / QCAD 2D',
      url: 'https://librecad.org/',
      offline: true,
    },
  },
  {
    slug: 'escuadras',
    name: 'Juego de Escuadras Profesionales (30°/60° y 45°)',
    category: 'arte',
    priority: 'P1',
    altText: 'Escuadras de acrílico sin bisel para dibujo técnico geométrico',
    aliases: ['juego-escuadras', 'escuadra-cartabon'],
    equivalenteVirtual: {
      nombre: 'GeoGebra Suite Geométrica',
      url: 'https://www.geogebra.org/geometry',
      offline: true,
    },
  },
  {
    slug: 'tablet-grafica',
    name: 'Tableta Digitalizadora con Lápiz Sensible a la Presión',
    category: 'computo',
    priority: 'P1',
    altText: 'Tableta gráfica digitalizadora USB para ilustración y diseño asistido',
    aliases: ['tableta-digitalizadora', 'pen-tablet'],
    equivalenteVirtual: {
      nombre: 'Photopea / Krita / Inkscape',
      url: 'https://www.photopea.com/',
      offline: false,
    },
  },

  // ── Lengua, Comunicación, Sonido y Audio ─────────────────────────────────
  {
    slug: 'micfono-usb',
    name: 'Micrófono de Condensador USB con Filtro Antipop',
    category: 'computo',
    priority: 'P1',
    altText: 'Micrófono USB para grabación de podcasts, entrevistas y debates orales',
    aliases: ['microfono-condensador', 'microfono-podcast'],
    equivalenteVirtual: {
      nombre: 'Audacity / BandLab Audio Studio',
      url: 'https://www.bandlab.com/',
      offline: true,
    },
  },
  {
    slug: 'audifonos',
    name: 'Audífonos de Diadema Aislantes de Ruido',
    category: 'computo',
    priority: 'P1',
    altText: 'Auriculares estéreo para laboratorio de idiomas y edición de audio',
    aliases: ['auriculares', 'diadema-audio'],
  },
  {
    slug: 'tarjetas-vocabulario',
    name: 'Tarjetas Didácticas y Fichas de Léxico (Flashcards)',
    category: 'arte',
    priority: 'P1',
    altText: 'Tarjetas impresas de vocabulario en inglés y raíces etimológicas',
    aliases: ['flashcards', 'fichas-lexicas'],
    equivalenteVirtual: {
      nombre: 'Quizlet / Anki Web Flashcards',
      url: 'https://quizlet.com/',
      offline: false,
    },
  },

  // ── Ciencias Sociales, Territorio y Campo ────────────────────────────────
  {
    slug: 'mapa-zona',
    name: 'Plano Cartográfico Municipal y Regional Impreso',
    category: 'medicion',
    priority: 'P1',
    altText: 'Mapa cartográfico del sector escolar con división comunitaria y relieve',
    aliases: ['mapa-territorial', 'croquis-comunitario'],
    equivalenteVirtual: {
      nombre: 'INEGI Mapa Digital de México / Google Earth',
      url: 'https://www.inegi.org.mx/app/mapa/espacioydatos/',
      offline: false,
    },
  },
  {
    slug: 'cuaderno-campo',
    name: 'Cuaderno y Bitácora de Registro de Campo',
    category: 'medicion',
    priority: 'P1',
    altText: 'Libreta de notas de campo para entrevistas comunitarias y observación',
    aliases: ['bitacora-campo', 'diario-campo'],
  },

  // ── Arte, Deporte y Expresión Socioemocional ─────────────────────────────
  {
    slug: 'material-arte',
    name: 'Kit de Materiales Artísticos (Pinturas, Pinceles, Lienzos)',
    category: 'arte',
    priority: 'P1',
    altText: 'Set de acuarelas, acrílicos, pinceles planos y cartulinas de ilustración',
    aliases: ['kit-pintura', 'pinceles-arte'],
    equivalenteVirtual: {
      nombre: 'Sketchpad / AutoDraw',
      url: 'https://sketch.io/sketchpad/',
      offline: false,
    },
  },
  {
    slug: 'balon',
    name: 'Balones Deportivos Reglamentarios (Básquetbol, Voleibol, Fútbol)',
    category: 'deportivo',
    priority: 'P1',
    altText: 'Balón oficial para activación física, torneos y hábitos saludables',
    aliases: ['balon-futbol', 'balon-basquetbol', 'pelota-deportiva'],
  },
  {
    slug: 'conos',
    name: 'Juego de Conos y Marcadores de Circuito Deportivo',
    category: 'deportivo',
    priority: 'P1',
    altText: 'Conos plásticos de delimitación de circuitos y pruebas de agilidad motriz',
    aliases: ['conos-entrenamiento', 'conos-deportivos'],
  },

  // ── Lote P2 — faltantes P1 y primera mitad de P2 (50) ────────────────────
  {
    slug: 'balanza-numeros',
    name: 'Balanza de Números Didáctica',
    category: 'medicion',
    priority: 'P2',
    altText: 'Balanza con dos platillos y fichas numéricas que muestran equivalencias entre ambos lados',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (balanzas y pesos)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'camara-tableta',
    name: 'Cámara Digital y Tableta de Captura',
    category: 'computo',
    priority: 'P2',
    altText: 'Cámara compacta apoyada junto a una tableta que muestra la misma toma capturada',
  },
  {
    slug: 'carpetas-archivo',
    name: 'Carpetas de Archivo de Suspensión',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Carpetas acartonadas con pestañas de colores y etiqueta en blanco en el frente',
  },
  {
    slug: 'compas-dibujo',
    name: 'Compás de Dibujo Técnico',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Compás metálico con puntas ajustables y tornillo, semiabierto en posición de trazo',
  },
  {
    slug: 'estacion-soldadura',
    name: 'Estación de Soldadura de Banco',
    category: 'industrial',
    priority: 'P2',
    altText: 'Inversor de soldadura con cable de pinza de masa, antorcha y mascarilla de protección',
    eppRequerido: ['Mascarilla de soldar', 'Guantes de soldar', 'Delantal de piel'],
  },
  {
    slug: 'kit-suelo',
    name: 'Kit de Análisis de Suelo',
    category: 'agro',
    priority: 'P2',
    altText: 'Muestra de tierra, tubo con agua destilada, tiras reactivas y tarjeta comparadora de colores',
    eppRequerido: ['Guantes de nitrilo'],
  },
  {
    slug: 'laptop-dev',
    name: 'Laptop de Desarrollo de Software',
    category: 'computo',
    priority: 'P2',
    altText: 'Laptop abierta con editor de código en pantalla y teclado retroiluminado',
    equivalenteVirtual: {
      nombre: 'VS Code for Web',
      url: 'https://vscode.dev/',
      offline: true,
    },
  },
  {
    slug: 'libro-digital',
    name: 'Lector de Libro Digital (E-reader)',
    category: 'computo',
    priority: 'P2',
    altText: 'E-reader vertical con marco fino, portada ilustrada genérica y borde de hojas visible',
  },
  {
    slug: 'parlante-bluetooth',
    name: 'Parlante Portátil Bluetooth',
    category: 'computo',
    priority: 'P2',
    altText: 'Parlante cilíndrico con rejilla texturizada, botones de control y argolla de carga',
  },
  {
    slug: 'plc-modulo',
    name: 'Módulo PLC Industrial',
    category: 'industrial',
    priority: 'P2',
    altText: 'Controlador lógico programable montado en riel DIN con terminales, LEDs y etiqueta',
  },
  {
    slug: 'router-switch',
    name: 'Router / Switch de Red',
    category: 'computo',
    priority: 'P2',
    altText: 'Equipo de red con antenas plegables, fila de puertos RJ45 y luces de actividad',
    equivalenteVirtual: {
      nombre: 'Cisco Packet Tracer',
      url: 'https://www.netacad.com/courses/packet-tracer',
      offline: true,
    },
  },
  {
    slug: 'sensor-inductivo',
    name: 'Sensor Inductivo Cilíndrico',
    category: 'industrial',
    priority: 'P2',
    altText: 'Sensor roscado de metal con cuerpo hexagonal, punta de detección y cable de conexión',
  },
  {
    slug: 'tarjetas-trabajo',
    name: 'Tarjetas de Trabajo Didácticas',
    category: 'arte',
    priority: 'P2',
    altText: 'Mazo de tarjetas con esquinas redondeadas, banda elástica y línea guía en la frontal',
  },
  {
    slug: 'termometro-alimentos',
    name: 'Termómetro Digital con Sonda para Alimentos',
    category: 'alimentos',
    priority: 'P2',
    altText: 'Termómetro de alimentos con sonda metálica, pantalla y mango antideslizante',
  },
  {
    slug: 'usb',
    name: 'Memoria USB Portátil',
    category: 'computo',
    priority: 'P2',
    altText: 'Memoria USB con cuerpo metálico mate y tapa descorrida en posición semiabierta',
  },
  {
    slug: 'afiche-mural',
    name: 'Afiche / Cartel Mural',
    category: 'arte',
    priority: 'P2',
    altText: 'Cartel de papel grueso con ilustración geométrica, sujeto con cinta en las esquinas',
  },
  {
    slug: 'alambre-ortodontico',
    name: 'Rollo de Alambre Ortodóntico',
    category: 'salud',
    priority: 'P2',
    altText: 'Alambre ortodóntico brillante con un tramo desenrollado doblado en forma de arco dental',
  },
  {
    slug: 'altavoz',
    name: 'Altavoz de Estante',
    category: 'fisica',
    priority: 'P2',
    altText: 'Altavoz con caja rectangular, rejilla frontal y cono de sonido visible',
  },
  {
    slug: 'archivo-historico',
    name: 'Archivo Histórico / Expedientes',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Pila de expedientes con cordones de atado, fotografía antigua y carpeta de cartón',
  },
  {
    slug: 'aspersor-riego',
    name: 'Aspersor de Riego',
    category: 'agro',
    priority: 'P2',
    altText: 'Aspersor con base y vástago proyectando un arco de gotas de agua',
    eppRequerido: ['Guantes de jardinería'],
  },
  {
    slug: 'autoclave',
    name: 'Autoclave de Laboratorio',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Recipiente metálico con tapa perillada, válvula de seguridad y manómetro circular',
    eppRequerido: ['Guantes térmicos', 'Gafas de seguridad'],
  },
  {
    slug: 'balanza-precision',
    name: 'Balanza de Precisión (0.01 g)',
    category: 'medicion',
    priority: 'P2',
    altText: 'Balanza analítica con campana protectora de vidrio, platina metálica y pantalla',
  },
  {
    slug: 'bandlab',
    name: 'Estudio de Audio Digital (BandLab)',
    category: 'virtual',
    priority: 'P2',
    altText: 'Tableta con interfaz de estudio de audio: pistas de ondas, canales y perillas',
    equivalenteVirtual: {
      nombre: 'BandLab Education',
      url: 'https://www.bandlab.com/',
      offline: true,
    },
  },
  {
    slug: 'bascula-almacen',
    name: 'Báscula de Piso para Almacén',
    category: 'logistica',
    priority: 'P2',
    altText: 'Báscula con plataforma metálica antideslizante y columna con pantalla de lectura',
  },
  {
    slug: 'bateria-plomo',
    name: 'Batería de Plomo-Ácido',
    category: 'energia',
    priority: 'P2',
    altText: 'Batería estacionaria con carcasa oscura, tapas selladas y bornes rojo y negro',
  },
  {
    slug: 'caja-tpv',
    name: 'Terminal de Punto de Venta (TPV)',
    category: 'servicios',
    priority: 'P2',
    altText: 'Terminal con pantalla inclinada, teclado de teclas y cajón de dinero con ranura',
  },
  {
    slug: 'calculadora-financiera',
    name: 'Calculadora Financiera',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Calculadora con teclas de función bicolores y teclado numérico en ángulo de tres cuartos',
  },
  {
    slug: 'camara-conteo',
    name: 'Cámara de Conteo Celular (Cámara de Peters)',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Disco de vidrio circular con retícula grabada y cubreobjetos superpuesto',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
  },
  {
    slug: 'camara-web',
    name: 'Cámara Web para Clases en Línea',
    category: 'computo',
    priority: 'P2',
    altText: 'Cámara web con lente central, clip para monitor, micrófono integrado y cable USB',
  },
  {
    slug: 'casos-etica',
    name: 'Tarjetas de Casos Éticos',
    category: 'arte',
    priority: 'P2',
    altText: 'Mazo de tarjetas con banda elástica e ilustración de balanza de justicia',
  },
  {
    slug: 'cera-dental',
    name: 'Cera Dental de Modelado e Instrumento de Encerado',
    category: 'salud',
    priority: 'P2',
    altText: 'Bloque de cera azul con acabado liso junto a instrumento de encerado de mango metálico',
  },
  {
    slug: 'cinta-metrica',
    name: 'Cinta Métrica Retráctil',
    category: 'medicion',
    priority: 'P2',
    altText: 'Cinta métrica en carcasa de goma con gancho metálico y tramo de cinta extendido',
  },
  {
    slug: 'cocina-industrial',
    name: 'Estufa / Cocina Industrial',
    category: 'alimentos',
    priority: 'P2',
    altText: 'Estufa de 4 quemadores con horno inferior, parrillas de rejilla y campana extractora',
    eppRequerido: ['Mandil', 'Cofia', 'Guantes térmicos'],
  },
  {
    slug: 'codigo-barras-app',
    name: 'Lector de Código de Barras Inalámbrico',
    category: 'logistica',
    priority: 'P2',
    altText: 'Lector pinchazo apuntando a una etiqueta de barras sobre una caja de paquetería',
  },
  {
    slug: 'controlador-carga',
    name: 'Controlador de Carga Solar',
    category: 'energia',
    priority: 'P2',
    altText: 'Caja con disipador de aletas, pantallita, bornes e indicadores luminosos',
  },
  {
    slug: 'cuestionario',
    name: 'Portapapeles con Cuestionario',
    category: 'arte',
    priority: 'P2',
    altText: 'Portapapeles de madera con hoja de casillas de verificación y lápiz con goma',
  },
  {
    slug: 'equipo-buceo',
    name: 'Equipo de Buceo (Máscara, Snorkel y Aletas)',
    category: 'deportivo',
    priority: 'P2',
    altText: 'Máscara con boquilla conectada al snorkel y un par de aletas al lado',
  },
  {
    slug: 'estanque-acuicola',
    name: 'Estanque Acuícola Circular',
    category: 'agro',
    priority: 'P2',
    altText: 'Estanque de fibra con bordes redondeados, agua clara y banco de siembra al fondo',
  },
  {
    slug: 'estufa-secado',
    name: 'Estufa de Secado de Laboratorio',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Gabinete metálico con puerta de vidrio, perillas de regulación y rejillas internas',
    eppRequerido: ['Guantes térmicos', 'Gafas de seguridad'],
  },
  {
    slug: 'frasco-muestreo',
    name: 'Frasco de Muestreo de Vidrio',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Frasco con tapa a rosca, superficie lisa y etiqueta en blanco adherida',
    eppRequerido: ['Guantes de nitrilo'],
  },
  {
    slug: 'fuente-historica',
    name: 'Fuente Histórica (Documento Antiguo)',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Rollo de documento parcialmente desenrollado con bordes envejecidos y sello de lacre',
  },
  {
    slug: 'glucometro',
    name: 'Glucómetro Digital',
    category: 'salud',
    priority: 'P2',
    altText: 'Equipo compacto con pantalla, botón y tira reactiva insertada en la ranura frontal',
  },
  {
    slug: 'goteros',
    name: 'Goteros de Vidrio con Bulbo',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Dos goteros de vidrio dispuestos en cruz con una gota suspendida en la punta',
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'gps-campo',
    name: 'Receptor GPS de Campo',
    category: 'medicion',
    priority: 'P2',
    altText: 'GPS con carcasa reforzada, antena corta y pantalla que muestra mapa con rutas',
  },
  {
    slug: 'hornillo-colado',
    name: 'Hornillo de Colado Dental (Mufla)',
    category: 'salud',
    priority: 'P2',
    altText: 'Hornillo redondo con puerta frontal, perilla de ajuste, pantalla y base estable',
  },
  {
    slug: 'invernadero',
    name: 'Invernadero de Túnel',
    category: 'agro',
    priority: 'P2',
    altText: 'Estructura metálica curva con cubierta plástica translúcida y bancadas de cultivo',
    eppRequerido: ['Guantes de jardinería', 'Calzado cerrado'],
  },
  {
    slug: 'jeringa-demo',
    name: 'Jeringa de Práctica sin Aguja',
    category: 'salud',
    priority: 'P2',
    altText: 'Jeringa de demostración con émbolo a medio recorrer y marcas de graduación',
    eppRequerido: ['Guantes de nitrilo'],
  },
  {
    slug: 'kit-agua',
    name: 'Kit de Análisis de Agua',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Botella con agua clara, tubo de ensayo y tira reactiva con franjas de colores',
    eppRequerido: ['Guantes de nitrilo', 'Gafas de seguridad'],
  },
  {
    slug: 'kit-calorimetria',
    name: 'Calorímetro de Vasos',
    category: 'fisica',
    priority: 'P2',
    altText: 'Caja de poliestireno con tapa, termómetro de aguja atravesándola y vaso interior',
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'kit-muestreo-agua',
    name: 'Kit de Muestreo de Agua',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Botella de polietileno con tapa a rosca, guantes de nitrilo doblados y etiqueta en blanco',
    eppRequerido: ['Guantes de nitrilo', 'Calzado cerrado'],
  },

  // ── Lote P3 — resto de matriz v1 (29) ────────────────────────────────────
  {
    slug: 'linea-tiempo',
    name: 'Tira de Línea del Tiempo',
    category: 'arte',
    priority: 'P2',
    altText: 'Tira de papel con línea horizontal, nodos circulares y banderitas de colores a lo largo del eje',
  },
  {
    slug: 'mapa-turistico',
    name: 'Mapa Turístico Plegado',
    category: 'servicios',
    priority: 'P2',
    altText: 'Mapa plegado con cuadrícula suave, iconos de puntos de interés y trayecto punteado con marcadores',
  },
  {
    slug: 'material-curacion',
    name: 'Set de Material de Curación',
    category: 'salud',
    priority: 'P2',
    altText: 'Rollo de gasa, venda elástica enrollada, tiras de apósito y frasco de solución antiséptica',
    eppRequerido: ['Guantes de nitrilo'],
  },
  {
    slug: 'materiales-arte',
    name: 'Materiales de Arte Escolar',
    category: 'arte',
    priority: 'P2',
    altText: 'Plastilina de colores, tijeras de punta roma, hojas de papel de colores y un pincel',
    equivalenteVirtual: {
      nombre: 'Sketchpad (Photopea / sketch.io)',
      url: 'https://sketch.io/sketchpad/',
      offline: true,
    },
  },
  {
    slug: 'mesa-luz',
    name: 'Mesa de Luz',
    category: 'arte',
    priority: 'P2',
    altText: 'Mesa de luz con superficie translúcida iluminada, regla en T y dos transparencias con formas superpuestas',
  },
  {
    slug: 'microcentrifuga',
    name: 'Microcentrífuga de Sobremesa',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Cuerpo redondo con tapa transparente, botón de arranque y rotor con microtubos',
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'nivel-agua',
    name: 'Nivel de Burbuja de Aluminio',
    category: 'construccion',
    priority: 'P2',
    altText: 'Nivel de burbuja con cuerpo rectangular y dos cápsulas de burbuja, horizontal y vertical',
  },
  {
    slug: 'oximetro-agua',
    name: 'Oxímetro de Agua (Disolución de Oxígeno)',
    category: 'agro',
    priority: 'P2',
    altText: 'Equipo portátil con pantalla, botones y sonda en cable con sensor de oxígeno',
  },
  {
    slug: 'panel-solar',
    name: 'Panel Solar Fotovoltaico',
    category: 'energia',
    priority: 'P2',
    altText: 'Panel con marco de aluminio, celdas cuadradas azul oscuro y soporte inclinado',
  },
  {
    slug: 'papel-albanene',
    name: 'Rollo de Papel Albania (Translúcido)',
    category: 'arte',
    priority: 'P2',
    altText: 'Rollo de papel translúcido con una hoja desenrollada que muestra su textura suave',
  },
  {
    slug: 'phmetro-industrial',
    name: 'pHímetro Industrial de Sobremesa',
    category: 'industrial',
    priority: 'P2',
    altText: 'Caja con pantalla grande, botones y electrodo en cable con junta de protección',
    eppRequerido: ['Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'pinza-amperometrica',
    name: 'Pinza Amperométrica',
    category: 'medicion',
    priority: 'P2',
    altText: 'Pinza amperométrica con pantalla, dial selector y pinza abierta en la parte superior',
  },
  {
    slug: 'placas-petri',
    name: 'Placas de Petri de Vidrio',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Par de placas apiladas y una abierta con medio de cultivo ámbar en el fondo',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'portafolio',
    name: 'Portafolio de Presentación',
    category: 'arte',
    priority: 'P2',
    altText: 'Carpeta de tapa dura con cierre elástico cruzado, esquinas reforzadas y hojas visibles al interior',
  },
  {
    slug: 'portobjetos',
    name: 'Laminillas Portaobjetos',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Placa de vidrio apilada con una muestra entre dos cubreobjetos en la parte superior',
    eppRequerido: ['Bata de laboratorio', 'Guantes de nitrilo'],
  },
  {
    slug: 'raspberry-pi',
    name: 'Placa Raspberry Pi',
    category: 'computo',
    priority: 'P2',
    altText: 'Placa verde compacta con puertos USB y HDMI, conector GPIO y microSD insertada',
  },
  {
    slug: 'refractometro',
    name: 'Refractómetro de Mano',
    category: 'medicion',
    priority: 'P2',
    altText: 'Refractómetro metálico con agarre, eyecup azul, botón de calibración y escala de lectura',
  },
  {
    slug: 'resistencias-kit',
    name: 'Juego de Resistencias',
    category: 'fisica',
    priority: 'P2',
    altText: 'Colector de resistencias con bandas de colores y varias sueltas en racimo al lado',
    equivalenteVirtual: {
      nombre: 'Falstad Circuit Simulator',
      url: 'https://www.falstad.com/circuit/',
      offline: true,
    },
  },
  {
    slug: 'rodillo-pintura',
    name: 'Rodillo de Pintura',
    category: 'construccion',
    priority: 'P2',
    altText: 'Rodillo con cubierta de pelo corto, eje metálico y mango ergonómico con gota de pintura en la punta',
    eppRequerido: ['Guantes de goma'],
  },
  {
    slug: 'sensores-arduino',
    name: 'Juego de Sensores para Arduino',
    category: 'computo',
    priority: 'P2',
    altText: 'Placa con sensor ultrasónico, módulo de luz y cable dupont enrollado al lado',
  },
  {
    slug: 'tensiometro',
    name: 'Tensiómetro Aneroide',
    category: 'salud',
    priority: 'P2',
    altText: 'Brazalete de tela con cierre, manómetro redondo y perilla de inflado con bomba',
  },
  {
    slug: 'termometro-ir',
    name: 'Termómetro Infrarrojo Tipo Pistola',
    category: 'medicion',
    priority: 'P2',
    altText: 'Termómetro infrarrojo con pantalla trasera, gatillo, sensor frontal y mango antideslizante',
  },
  {
    slug: 'transportador',
    name: 'Transportador de 180°',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Transportador transparente con escala de gradaciones, línea de base recta y agujero central',
  },
  {
    slug: 'tuberia-pvc',
    name: 'Tubería de PVC con Codo',
    category: 'construccion',
    priority: 'P2',
    altText: 'Tramo de tubería blanca con codo de 90° y junta tórica en composición horizontal',
  },
  {
    slug: 'tubo-ensayo',
    name: 'Tubos de Ensayo con Rack',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Tres tubos de vidrio con líquido claro hasta la mitad, sostenidos en un rack plástico',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
  },
  {
    slug: 'uniform-hospedaje',
    name: 'Uniforme de Hospedaje',
    category: 'servicios',
    priority: 'P2',
    altText: 'Chaqueta con solapas y botones, gorro rígido de conserje y corbata presentados como conjunto',
  },
  {
    slug: 'vajilla-demo',
    name: 'Vajilla de Demostración (Mise en Place)',
    category: 'servicios',
    priority: 'P2',
    altText: 'Plato llano, plato hondo, taza con plato y par de cubiertos alineados',
  },
  {
    slug: 'vinil-imprenta',
    name: 'Rollo de Vinil Adhesivo de Imprenta',
    category: 'arte',
    priority: 'P2',
    altText: 'Rollo con tramo desenrollado y esquina levantada que muestra la capa de soporte',
  },
  {
    slug: 'yeso-dental',
    name: 'Yeso Dental y Arcada de Modelo',
    category: 'salud',
    priority: 'P2',
    altText: 'Cubeta flexible con yeso blanco, espátula de metal y modelo de arcada de yeso al lado',
  },

  // ── Lote P4 — Pensamiento Matemático y FFEO matemática (29) ──────────────
  {
    slug: 'abaco',
    name: 'Ábaco de Madera',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Ábaco de madera con 10 barras horizontales y cuentas deslizantes de colores',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'tarjetas-numeradas',
    name: 'Tarjetas Numéricas',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Mazo de tarjetas con un dígito grande por tarjeta, la del frente ligeramente separada',
  },
  {
    slug: 'fichas-conteo',
    name: 'Fichas de Conteo de Colores',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Montón de fichas redondas de plástico de colores dispuestas en superficie plana',
  },
  {
    slug: 'regletas-cuisenaire',
    name: 'Regletas Cuisenaire',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Juego de regletas ordenadas en escalera, de colores y longitudes crecientes',
  },
  {
    slug: 'recta-numerica',
    name: 'Recta Numérica (Lámina)',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Lámina con recta horizontal, marcas equidistantes, punto de origen y flechas en los extremos',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (recta numérica)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'bloques-geometricos',
    name: 'Bloques Geométricos de Madera',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Cubo, esfera, cilindro y cono de madera alineados sobre superficie plana',
  },
  {
    slug: 'tangram',
    name: 'Tangram de Madera',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Tangram con sus 7 piezas formando un cuadrado perfecto',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (tangram)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'regla-graduada',
    name: 'Regla Escolar de 30 cm',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Regla rígida con marcas de graduación, bordes rectos y extremos a escuadra',
  },
  {
    slug: 'balanza-cocina',
    name: 'Balanza de Cocina Analógica',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Balanza con platillo circular, base estable y aguja marcadora de peso',
  },
  {
    slug: 'fichas-fracciones',
    name: 'Fichas de Fracciones',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Fichas rectangulares divididas en partes iguales con banda de color por fracción',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (fracciones)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'discos-fracciones',
    name: 'Discos de Fracciones',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Discos divididos en sectores de mitades, tercios y cuartos apilados con uno al frente',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (fracciones)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'bloques-patrones',
    name: 'Bloques de Patrones (Serie Lineal)',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Serie lineal de bloques de colores alternados que forman un patrón repetitivo',
  },
  {
    slug: 'papel-milimetrado',
    name: 'Papel Milimetrado',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Hoja de papel con cuadrícula fina ligeramente enrollada en un borde',
  },
  {
    slug: 'balanza-algebraica',
    name: 'Balanza Algebraica de Dos Platos',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Balanza con base, varilla central y fichas equivalentes en cada platillo',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (balanza)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'coordenadas-cartesianas',
    name: 'Plano Cartesiano (Lámina)',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Lámina con ejes perpendiculares, cuadrícula y puntos destacados sobre el plano',
    equivalenteVirtual: {
      nombre: 'GeoGebra',
      url: 'https://www.geogebra.org/geometry',
      offline: true,
    },
  },
  {
    slug: 'cuerpos-geometricos',
    name: 'Cuerpos Geométricos Translúcidos',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Cubo, esfera, cilindro, cono y pirámide de material translúcido alineados',
  },
  {
    slug: 'poligonos-recortables',
    name: 'Polígonos Recortables',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Polígonos de cartulina recortados en triángulo, cuadrado, pentágono y hexágono superpuestos',
  },
  {
    slug: 'urna-probabilidad',
    name: 'Urna Transparente de Probabilidad',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Urna transparente con tapa y bolitas de colores en su interior',
    equivalenteVirtual: {
      nombre: 'PhET Plinko Probability',
      url: 'https://phet.colorado.edu/es/simulations/plinko-probability',
      offline: true,
    },
  },
  {
    slug: 'kit-estadistica',
    name: 'Kit de Estadística',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Fichas de colores para clasificar junto a tarjeta de registro con columnas vacías',
  },
  {
    slug: 'calculadora-cientifica',
    name: 'Calculadora Científica',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Calculadora con pantalla superior, teclado numérico y teclas de funciones',
    equivalenteVirtual: {
      nombre: 'Desmos',
      url: 'https://www.desmos.com/calculator',
      offline: true,
    },
  },
  {
    slug: 'fichas-monetarias',
    name: 'Fichas de Dinero Didácticas',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Fichas redondas de colores y rectángulos lisos que simulan monedas y billetes sin impresos',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (dinero)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'tablero-100',
    name: 'Tablero de Conteo 10 × 10',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Tablero de 100 casillas vacías con fichas de colores colocadas en algunas casillas',
    equivalenteVirtual: {
      nombre: 'Polypad Mathigon (tableros)',
      url: 'https://mathigon.org/polypad',
      offline: true,
    },
  },
  {
    slug: 'domino-numerico',
    name: 'Fichas de Dominó Numérico',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Fichas de dominó con puntos negros por cara, dos en pie y tres apoyadas',
  },
  {
    slug: 'fichas-decimales',
    name: 'Barras Decimales de Plástico',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Barras divididas en 10 partes iguales apiladas con una al frente',
  },
  {
    slug: 'mosaico-area',
    name: 'Mosaico de Área',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Piezas cuadradas de colores en cuadrícula formando un rectángulo sobre una superficie',
  },
  {
    slug: 'disco-porcentaje',
    name: 'Disco de Porcentaje',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Disco dividido en sectores de distinto tamaño con un sector de color destacado',
  },
  {
    slug: 'grafica-barras',
    name: 'Gráfica de Barras en Cartulina',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Gráfica con cinco barras de alturas distintas y eje en L, sin texto',
    equivalenteVirtual: {
      nombre: 'Desmos',
      url: 'https://www.desmos.com/calculator',
      offline: true,
    },
  },
  {
    slug: 'figuras-semejantes',
    name: 'Figuras Semejantes (Triángulos)',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Dos triángulos de distinto tamaño en proporción con líneas punteadas que marcan la correspondencia',
  },
  {
    slug: 'triangulo-rectangulo',
    name: 'Plantilla de Triángulo Rectángulo',
    category: 'matematicas',
    priority: 'P2',
    altText: 'Plantilla de acrílico con ángulo recto marcado y cantos biselados',
  },

  // ── Lote P5 — Currículum Fundamental, FFEO, Socioemocional y EPP (48) ────
  {
    slug: 'cilindro-graduado',
    name: 'Cilindro Graduado de Vidrio',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Cilindro de vidrio con líquido y escala milimétrica grabada en el cuerpo',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
  },
  {
    slug: 'matraz-aforado',
    name: 'Matraz Aforado de Vidrio',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Matraz de vidrio con cuello largo, anillo de calibración y líquido claro en el fondo',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
  },
  {
    slug: 'pipeta',
    name: 'Pipeta de Vidrio con Pera de Goma',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Pipeta de vidrio con pera de goma en un extremo y marca de aforo en el cuerpo',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'pendulo',
    name: 'Péndulo Simple con Soporte',
    category: 'fisica',
    priority: 'P2',
    altText: 'Hilo con plomada metálica colgando de un soporte con base estable',
    equivalenteVirtual: {
      nombre: 'PhET Pendulum Lab',
      url: 'https://phet.colorado.edu/es/simulations/pendulum-lab',
      offline: true,
    },
  },
  {
    slug: 'rampa-fisica',
    name: 'Rampa Inclinable con Carro',
    category: 'fisica',
    priority: 'P2',
    altText: 'Rampa con riel de guía e inclinación ajustable y un carro pequeño en la parte superior',
  },
  {
    slug: 'kit-reactivos',
    name: 'Kit de Reactivos',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Tres frascos con líquidos de colores y portaetiquetas en blanco alineados',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'kit-diseccion',
    name: 'Kit de Disección',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Bandeja de cera con bisturí, pinzas y pinza de fijación dispuestos en orden',
    eppRequerido: ['Bata de laboratorio', 'Guantes de nitrilo'],
  },
  {
    slug: 'triptico',
    name: 'Tríptico Plegado en Tres Paneles',
    category: 'arte',
    priority: 'P2',
    altText: 'Papel plegado en tres paneles con diseño geométrico abstracto en la portada',
  },
  {
    slug: 'etiquetadora-red',
    name: 'Etiquetadora de Cables',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Etiquetadora con rótulo en blanco insertado y carcasa ergonómica de agarre',
  },
  {
    slug: 'lamparitas',
    name: 'Bombillas Incandescentes con Base Roscada',
    category: 'construccion',
    priority: 'P2',
    altText: 'Par de bombillas con base roscada metálica, una en pie y otra apoyada de lado',
  },
  {
    slug: 'medidor-energia',
    name: 'Medidor de Consumo Energético (Enchufe Inteligente)',
    category: 'energia',
    priority: 'P2',
    altText: 'Enchufe inteligente con pantalla pequeña y botón de control en la frontal',
  },
  {
    slug: 'aros',
    name: 'Aros de Gimnasia',
    category: 'deportivo',
    priority: 'P2',
    altText: 'Tres aros de gimnasia apilados con cinta de colores en las empuñaduras',
  },
  {
    slug: 'cuerdas-deportivas',
    name: 'Cuerda de Saltar',
    category: 'deportivo',
    priority: 'P2',
    altText: 'Cuerda de saltar enrollada con manijas de goma ergonómicas',
  },
  {
    slug: 'tarjetas-emociones',
    name: 'Tarjetas de Emociones',
    category: 'arte',
    priority: 'P2',
    altText: 'Mazo de tarjetas con ilustraciones de caras expresivas y banda elástica',
  },
  {
    slug: 'mapa-mental',
    name: 'Mapa Mental (Plantilla en Blanco)',
    category: 'arte',
    priority: 'P2',
    altText: 'Mapa mental con nodo central y ramas curvas con círculos vacíos, sin texto',
  },
  {
    slug: 'guantes-seguridad',
    name: 'Guantes de Seguridad de Nitrilo',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Par de guantes de nitrilo doblados con textura antideslizante en las yemas',
  },
  {
    slug: 'gafas-seguridad',
    name: 'Gafas de Seguridad',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Gafas de protección con lente transparente y marco blanco',
  },
  {
    slug: 'cubrebocas',
    name: 'Cubrebocas Desechable de 3 Capas',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Cubrebocas desechable con pliegues frontales y orejeras elásticas',
  },
  {
    slug: 'agitador-magnetico',
    name: 'Agitador Magnético de Laboratorio',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Aparato con plato redondo, perilla de velocidad y vaso de cristal encima',
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'kit-adn',
    name: 'Kit de Extracción de ADN',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Tubo con alcohol frío, jarra con solución, filtro de café y frasco de detergente',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'lupa',
    name: 'Lupa de Mano con Soporte',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Lupa de mano con mango acolchado y lente de aumento apoyada sobre soporte',
  },
  {
    slug: 'kit-tincion',
    name: 'Kit de Tinciones',
    category: 'laboratorio_bio',
    priority: 'P2',
    altText: 'Tres viales de colorantes azul, rojo y violeta con gotero en el tapón',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad', 'Guantes de nitrilo'],
  },
  {
    slug: 'capacitores-kit',
    name: 'Juego de Capacitores',
    category: 'fisica',
    priority: 'P2',
    altText: 'Capacitores de distintos valores ordenados en un colector plástico de hileras',
    equivalenteVirtual: {
      nombre: 'Falstad Circuit Simulator',
      url: 'https://www.falstad.com/circuit/',
      offline: true,
    },
  },
  {
    slug: 'cable-banana',
    name: 'Cables de Montaje con Plugas BANANA',
    category: 'fisica',
    priority: 'P2',
    altText: 'Par de cables rojo y negro con plugas banana en ambos extremos',
  },
  {
    slug: 'sensor-movimiento',
    name: 'Sensor de Movimiento / Infrarrojo',
    category: 'fisica',
    priority: 'P2',
    altText: 'Sensor con módulo de bola, cable y soporte metálico de montaje',
  },
  {
    slug: 'cartabon',
    name: 'Cartabón Transparente 45° / 30°-60°',
    category: 'arte',
    priority: 'P2',
    altText: 'Cartabón transparente con bordes biselados y escala de gradaciones en los lados',
  },
  {
    slug: 'portaminas',
    name: 'Portaminas Metálico',
    category: 'arte',
    priority: 'P2',
    altText: 'Portaminas de metal con punta ajustable y borrador en la tapa superior',
  },
  {
    slug: 'lapices-grafito',
    name: 'Lápices de Grafito con Afilador',
    category: 'arte',
    priority: 'P2',
    altText: 'Tres lápices de grafito con extremos sin afilar junto a un afilador metálico',
  },
  {
    slug: 'borrador-tecnico',
    name: 'Borrador Técnico con Funda',
    category: 'arte',
    priority: 'P2',
    altText: 'Borrador blando y rectangular dentro de su funda protectora',
  },
  {
    slug: 'regla-t',
    name: 'Regla en T de Acrílico',
    category: 'arte',
    priority: 'P2',
    altText: 'Regla en T transparente con mango ergonómico y canto recto para mesa de dibujo',
  },
  {
    slug: 'plantillas-dibujo',
    name: 'Plantilla de Formas Técnicas',
    category: 'arte',
    priority: 'P2',
    altText: 'Plantilla con recortes de círculos, elipses y polígonos y mango de agarre',
  },
  {
    slug: 'tarjetas-percepcion',
    name: 'Tarjetas de Percepción / Ilusiones Ópticas',
    category: 'arte',
    priority: 'P2',
    altText: 'Mazo de tarjetas apiladas con ilustraciones ópticas geométricas en la frontal',
  },
  {
    slug: 'revistas-recorte',
    name: 'Revistas para Recorte',
    category: 'arte',
    priority: 'P2',
    altText: 'Pila de revistas abiertas con páginas de imágenes recortadas y tijeras al lado',
  },
  {
    slug: 'estadiometro',
    name: 'Estadiómetro de Pared',
    category: 'salud',
    priority: 'P2',
    altText: 'Vara graduada montada en pared con nivelador y base de apoyo',
  },
  {
    slug: 'libro-mayor',
    name: 'Libro Mayor Contable',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Libro mayor abierto con renglones y columnas en blanco, sin cifras',
  },
  {
    slug: 'bata-laboratorio',
    name: 'Bata de Laboratorio Blanca',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Bata blanca colgada con botones delanteros y dos bolsillos inferiores',
  },
  {
    slug: 'gradilla',
    name: 'Gradilla para Tubos de Ensayo',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Gradilla de plástico con seis oquedades para sostener tubos de ensayo',
  },
  {
    slug: 'matraz-balon',
    name: 'Matraz de Fondo Redondo (Balón)',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Matraz de vidrio con cuello largo y esfera inferior que contiene líquido claro',
    eppRequerido: ['Bata de laboratorio', 'Gafas de seguridad'],
  },
  {
    slug: 'vidrio-reloj',
    name: 'Vidrio de Reloj',
    category: 'laboratorio_quimica',
    priority: 'P2',
    altText: 'Disco de vidrio circular con borde redondeado apoyado ligeramente inclinado',
  },
  {
    slug: 'brujula',
    name: 'Brújula Escolar',
    category: 'medicion',
    priority: 'P2',
    altText: 'Brújula con carcasa redonda, aguja norte-sur visible y anillo graduado',
  },
  {
    slug: 'robot-basico',
    name: 'Robot Escolar de Dos Ruedas',
    category: 'computo',
    priority: 'P2',
    altText: 'Chasis con dos ruedas, sensor ultrasónico frontal y cable de conexión',
  },
  {
    slug: 'led-kit',
    name: 'Juego de Diodos LED de Colores',
    category: 'fisica',
    priority: 'P2',
    altText: 'Cinco diodos LED de colores con patas dobladas alineados en fila',
    equivalenteVirtual: {
      nombre: 'Falstad Circuit Simulator',
      url: 'https://www.falstad.com/circuit/',
      offline: true,
    },
  },
  {
    slug: 'prisma-optico',
    name: 'Prisma Óptico de Vidrio',
    category: 'fisica',
    priority: 'P2',
    altText: 'Prisma triangular de vidrio atravesado por un haz de luz que se dispersa en colores',
    equivalenteVirtual: {
      nombre: 'PhET Bending Light',
      url: 'https://phet.colorado.edu/es/simulations/bending-light',
      offline: true,
    },
  },
  {
    slug: 'estetoscopio',
    name: 'Estetoscopio',
    category: 'salud',
    priority: 'P2',
    altText: 'Estetoscopio con brazalete metálico, tubo en Y y auriculares acolchados',
  },
  {
    slug: 'termometro-clinico',
    name: 'Termómetro Clínico Digital',
    category: 'salud',
    priority: 'P2',
    altText: 'Termómetro digital con punta metálica y pantalla pequeña en el mango',
  },
  {
    slug: 'botiquin',
    name: 'Botiquín de Emergencia',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Maletín con cruz roja en la tapa abierto para mostrar vendas y gasa en el interior',
  },
  {
    slug: 'extintor',
    name: 'Extintor de Incendio',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Extintor rojo con manguera, pasamanos superior y manómetro en la base',
  },
  {
    slug: 'caballete-pintura',
    name: 'Caballete de Madera con Lienzo',
    category: 'arte',
    priority: 'P2',
    altText: 'Caballete de tres patas con un lienzo en blanco apoyado en la repisa',
  },

  // ── Lote P6 — FFE Laboral / Formación para el Trabajo y Carreras BT (35) ─
  {
    slug: 'perforadora',
    name: 'Perforadora de Papel de 3 Orificios',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Perforadora con palanca metálica y base en forma de U para tres orificios',
  },
  {
    slug: 'sello-fechador',
    name: 'Sello Fechador de Troquel',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Sello redondo con mango de plástico y banda de tinta incorporada',
  },
  {
    slug: 'grapadora',
    name: 'Grapadora de Oficina',
    category: 'ofimatica',
    priority: 'P2',
    altText: 'Grapadora con base de goma, brazo articulado y bandeja de grapas visible',
  },
  {
    slug: 'etiquetador-precio',
    name: 'Etiquetador de Precios',
    category: 'servicios',
    priority: 'P2',
    altText: 'Etiquetador con pantalla pequeña, gatillo y rollo de etiquetas en blanco',
  },
  {
    slug: 'muestrario-productos',
    name: 'Muestrario de Tienda',
    category: 'servicios',
    priority: 'P2',
    altText: 'Estante pequeño con cajas y botellas de colores lisos sin etiquetas',
  },
  {
    slug: 'macetas-horticolas',
    name: 'Macetas Hortícolas con Plántulas',
    category: 'agro',
    priority: 'P2',
    altText: 'Tres macetas de plástico de colores con sustrato y plántula joven en la del centro',
    eppRequerido: ['Guantes de jardinería'],
  },
  {
    slug: 'red-insectos',
    name: 'Red de Captura de Insectos',
    category: 'agro',
    priority: 'P2',
    altText: 'Aro de malla sobre mango largo de madera en posición de captura',
  },
  {
    slug: 'manguera-riego',
    name: 'Manguera de Jardín con Boquilla',
    category: 'agro',
    priority: 'P2',
    altText: 'Manguera enrollada con boquilla de aerosol metálica en la punta',
    eppRequerido: ['Guantes de jardinería'],
  },
  {
    slug: 'tarros-farmacia',
    name: 'Tarros de Farmacia de Vidrio',
    category: 'salud',
    priority: 'P2',
    altText: 'Tres frascos de vidrio con tapa a rosca y contenido granulado, sin etiquetas',
  },
  {
    slug: 'cartulinas',
    name: 'Pila de Cartulinas de Colores',
    category: 'arte',
    priority: 'P2',
    altText: 'Pila de cartulinas de colores con una esquina levantada',
  },
  {
    slug: 'cartuchos-tinta',
    name: 'Cartuchos de Tinta Genéricos',
    category: 'computo',
    priority: 'P2',
    altText: 'Dos cartuchos de tinta, uno cian y uno negro, con contactos metálicos visibles',
  },
  {
    slug: 'taladro',
    name: 'Taladro Eléctrico de Percusión',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Taladro con cable, asa lateral y broca insertada en el portabrocas',
    eppRequerido: ['Gafas de seguridad'],
  },
  {
    slug: 'cinta-aisladora',
    name: 'Rollo de Cinta Aisladora',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Rollo de cinta negra con un tramo desenrollado en diagonal',
  },
  {
    slug: 'cable-electrico',
    name: 'Trozo de Cable Eléctrico',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Cable con las puntas peladas que muestran el conductor de cobre',
  },
  {
    slug: 'plano-electrico',
    name: 'Plano de Instalación Eléctrica',
    category: 'construccion',
    priority: 'P2',
    altText: 'Plano plegado con líneas, símbolos geométricos y cruces, sin texto',
  },
  {
    slug: 'llave-francesa',
    name: 'Llave Francesa Metálica',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Llave con boca ajustable y mango forrado en material antideslizante',
    eppRequerido: ['Guantes mecánicos'],
  },
  {
    slug: 'casco-seguridad',
    name: 'Casco de Seguridad',
    category: 'seguridad_epp',
    priority: 'P2',
    altText: 'Casco amarillo con banda interior y borde pronunciado',
  },
  {
    slug: 'regla-metalica',
    name: 'Regla Metálica de 30 cm',
    category: 'herramientas',
    priority: 'P2',
    altText: 'Regla de acero con marcas de graduación y canto recto',
  },
  {
    slug: 'pinza-ortodoncia',
    name: 'Pinza Ortodóntica',
    category: 'salud',
    priority: 'P2',
    altText: 'Pinza de puntas finas y curvas con ajustes antideslizantes',
  },
  {
    slug: 'articulador-dental',
    name: 'Articulador Dental Metálico',
    category: 'salud',
    priority: 'P2',
    altText: 'Articulador con tornillos de ajuste y base en forma de horquilla',
  },
  {
    slug: 'fresas-dentales',
    name: 'Juego de Fresas Dentales',
    category: 'salud',
    priority: 'P2',
    altText: 'Cinco fresas con mango metálico y puntas de distinto corte alineadas',
  },
  {
    slug: 'moldes-reposteria',
    name: 'Moldes Metálicos de Repostería',
    category: 'alimentos',
    priority: 'P2',
    altText: 'Tres moldes metálicos de figuras geométricas apilados',
    eppRequerido: ['Mandil', 'Cofia'],
  },
  {
    slug: 'licuadora',
    name: 'Licuadora de Vaso',
    category: 'alimentos',
    priority: 'P2',
    altText: 'Licuadora con vaso, tapa, asa y panel de botones en la base',
    eppRequerido: ['Mandil'],
  },
  {
    slug: 'frasco-conserva',
    name: 'Frasco de Conserva con Tapa Hermética',
    category: 'alimentos',
    priority: 'P2',
    altText: 'Frasco de vidrio con tapa hermética y goma selladora en el borde',
  },
  {
    slug: 'delantal-cocina',
    name: 'Delantal de Cocina',
    category: 'alimentos',
    priority: 'P2',
    altText: 'Delantal de tela con correa de cuello y lazo trasero',
  },
  {
    slug: 'pc-abierto',
    name: 'Computadora de Escritorio Abierta',
    category: 'computo',
    priority: 'P2',
    altText: 'Gabinete con costado retirado que muestra fuente, tarjeta y cables internos',
  },
  {
    slug: 'disco-externo',
    name: 'Disco de Almacenamiento Externo',
    category: 'computo',
    priority: 'P2',
    altText: 'Disco rectangular con superficie mate y cable USB conectado',
  },
  {
    slug: 'maleta-exhibicion',
    name: 'Maleta de Exhibición',
    category: 'servicios',
    priority: 'P2',
    altText: 'Maleta abierta con ropa doblada de colores lisos organizada en compartimentos',
  },
  {
    slug: 'torno-mecanico',
    name: 'Torno Mecánico de Banco',
    category: 'industrial',
    priority: 'P2',
    altText: 'Torno con plato, carro longitudinal y herramienta de corte soportada en torreta',
    eppRequerido: ['Gafas de seguridad', 'Calzado cerrado'],
  },
  {
    slug: 'compresor-aire',
    name: 'Compresor de Aire',
    category: 'industrial',
    priority: 'P2',
    altText: 'Compresor con tanque cilíndrico, manómetro y manguera enrollada',
    eppRequerido: ['Gafas de seguridad', 'Protectores auditivos'],
  },
  {
    slug: 'soldadura-mig',
    name: 'Equipo de Soldadura MIG',
    category: 'industrial',
    priority: 'P2',
    altText: 'Máquina sobre ruedas con antorcha y cable de masa en espiral',
    eppRequerido: ['Mascarilla de soldar', 'Guantes de soldar', 'Delantal de piel'],
  },
  {
    slug: 'red-pesca',
    name: 'Red de Pesca con Boyas',
    category: 'deportivo',
    priority: 'P2',
    altText: 'Red enrollada con boyas naranjas y plomos de hundimiento',
  },
  {
    slug: 'estanteria-almacen',
    name: 'Estante Metálico de Almacén',
    category: 'logistica',
    priority: 'P2',
    altText: 'Estante de tres niveles con cajas de cartón apoyadas en cada nivel',
  },
  {
    slug: 'lector-codigo-barras',
    name: 'Lector de Código de Barras de Mano',
    category: 'logistica',
    priority: 'P2',
    altText: 'Lector con cable y haz rojo de escaneo apuntando hacia adelante',
  },
  {
    slug: 'motor-universal',
    name: 'Motor Eléctrico Universal',
    category: 'industrial',
    priority: 'P2',
    altText: 'Motor con eje, polea en el extremo y bornes de conexión en la carcasa',
  },
];

const CATALOG_BY_SLUG = new Map<string, MaterialCatalogItem>(
  MATERIALES_CATALOG.map((item) => [item.slug, item])
);

// Mapeo inverso de alias a slug principal (soporta variantes con y sin tildes)
const ALIAS_TO_SLUG = new Map<string, string>();
for (const item of MATERIALES_CATALOG) {
  if (item.aliases) {
    for (const alias of item.aliases) {
      const lower = alias.toLowerCase();
      ALIAS_TO_SLUG.set(lower, item.slug);
      const unaccented = lower.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
      ALIAS_TO_SLUG.set(unaccented, item.slug);
    }
  }
}

/**
 * Busca un material por su slug exacto o por cualquiera de sus alias registrados.
 */
export function getMaterial(slugOrAlias: string): MaterialCatalogItem | undefined {
  if (!slugOrAlias) return undefined;
  const normalized = slugOrAlias.trim().toLowerCase();
  const direct = CATALOG_BY_SLUG.get(normalized);
  if (direct) return direct;
  const unaccented = normalized.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const canonicalSlug = ALIAS_TO_SLUG.get(normalized) || ALIAS_TO_SLUG.get(unaccented);
  return canonicalSlug ? CATALOG_BY_SLUG.get(canonicalSlug) : undefined;
}

/**
 * Deriva las rutas de assets de imagen para un slug dado (D3).
 */
export function getMaterialImagePaths(slug: string): { png: string; placeholder: string } {
  const cleanSlug = slug.trim().toLowerCase();
  return {
    png: `/images/materiales/${cleanSlug}.png`,
    placeholder: '/images/materiales/_placeholder.png',
  };
}
