/**
 * agropecuaria.ts — Familia Tecnológica: Agropecuaria, Agroindustrias y Recursos Hídricos
 * SIGPDA-EMS · SEMS Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const AGROPECUARIA_CATALOG: CatalogItem[] = [
  {
    id: 'barrena_suelo',
    name: 'Barrena Muestreadora de Suelo (Tipo Holandesa)',
    category: 'agropecuaria',
    englishQuery: 'soil auger sampler sampling tool agriculture',
    aliases: ['barrena', 'barrena de suelo', 'barrena muestreadora', 'muestreador de suelo', 'soil auger'],
    keywordsBilingual: ['soil auger', 'soil sampler', 'barrena', 'muestreo', 'edafologia', 'soil'],
    technicalRole: 'Extracción de muestras representativas de suelo a profundidades de 0-20 cm y 20-40 cm para análisis físico-químico y fertilidad',
    safetyRule: 'Limpiar la cuchilla espiral entre muestra y muestra para evitar contaminación cruzada de nutrientes',
    normaNOM: 'NOM-021-SEMARNAT-2000',
    familias: ['agropecuaria'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'potenciometro_campo_ph',
    name: 'Potenciómetro / Medidor de pH de Suelo y Soluciones',
    category: 'instrumento_medicion',
    englishQuery: 'digital ph meter soil water tester agriculture',
    aliases: ['phmetro', 'peachimetro', 'medidor de ph', 'potenciometro de suelo', 'ph meter'],
    keywordsBilingual: ['ph meter', 'potenciometro', 'soil ph', 'acidity', 'alkalinity', 'buffer'],
    technicalRole: 'Medición de la acidez o alcalinidad (pH) en soluciones de fertirriego y extracto de pasta de suelo saturada',
    safetyRule: 'Calibrar con soluciones buffer de pH 4.01 y 7.00 y mantener el electrodo de vidrio sumergido en solución de almacenamiento KCl',
    normaNOM: 'NOM-021-SEMARNAT-2000',
    familias: ['agropecuaria', 'biotecnologia', 'ciencias_experimentales'],
    svgKey: 'multimetro',
  },
  {
    id: 'conductimetro_campo',
    name: 'Conductímetro Portátil (Medidor de Conductividad CE)',
    category: 'instrumento_medicion',
    englishQuery: 'electrical conductivity meter ec meter soil agriculture',
    aliases: ['conductimetro', 'medidor de conductividad', 'ec meter', 'salinometro', 'conductímetro'],
    keywordsBilingual: ['conductivity meter', 'ec meter', 'conductimetro', 'salinity', 'ds/m'],
    technicalRole: 'Determinación de la salinidad del agua de riego y disponibilidad de sales fertilizantes en dS/m o mS/cm',
    safetyRule: 'Enjuagar la celda con agua desionizada después de cada lectura en soluciones nutritivas concentradas',
    normaNOM: 'NOM-021-SEMARNAT-2000',
    familias: ['agropecuaria', 'biotecnologia'],
    svgKey: 'multimetro',
  },
  {
    id: 'refractometro_brix',
    name: 'Refractómetro Óptico / Digital Grados Brix',
    category: 'instrumento_medicion',
    englishQuery: 'optical refractometer brix sugar content agriculture food',
    aliases: ['refractometro', 'refractómetro', 'refractometro brix', 'medidor de brix', 'brix refractometer'],
    keywordsBilingual: ['refractometer', 'refractometro', 'brix', 'sugar', 'refraction', 'harvest'],
    technicalRole: 'Medición del porcentaje de azúcares solubles (°Brix) en savia de plantas, frutos y pulpas para índice de madurez de cosecha',
    safetyRule: 'Limpiar el prisma óptico con papel lente suave y agua destilada sin frotar con materiales abrasivos',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['agropecuaria', 'gastronomia', 'biotecnologia'],
    svgKey: 'vernier',
  },
  {
    id: 'lactodensimetro_quevenne',
    name: 'Lactodensímetro Quevenne / Termolactodensímetro',
    category: 'instrumento_medicion',
    englishQuery: 'lactometer milk hydrometer dairy testing',
    aliases: ['lactodensimetro', 'lactodensímetro', 'densimetro de leche', 'lactometer', 'termolactodensimetro'],
    keywordsBilingual: ['lactometer', 'milk hydrometer', 'densimetro', 'leche', 'dairy density', 'quevenne'],
    technicalRole: 'Determinación de la densidad relativa de la leche cruda (1.028 a 1.034 g/mL a 15°C) para detección de adulteración con agua',
    safetyRule: 'Realizar la lectura al nivel del menisco superior y aplicar la corrección por temperatura termométrica correspondiente',
    normaNOM: 'NOM-155-SCFI-2012',
    familias: ['agropecuaria', 'gastronomia'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'mochila_aspersora',
    name: 'Mochila Aspersora Manual con Boquilla de Abanico',
    category: 'agropecuaria',
    englishQuery: 'backpack sprayer knapsack sprayer agriculture',
    aliases: ['mochila aspersora', 'aspersora', 'bomba de aspersión', 'bomba aspersora', 'fumigadora de mochila', 'knapsack sprayer'],
    keywordsBilingual: ['backpack sprayer', 'sprayer', 'aspersora', 'nozzle', 'pesticide', 'fumigation'],
    technicalRole: 'Aplicación dosificada de biofertilizantes, abonos foliares y productos fitosanitarios con presión hidráulica constante',
    safetyRule: 'Uso estricto de EPP completo: mascarilla con cartucho químico para vapores, googles, guantes de nitrilo y overol impermeable',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['agropecuaria'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'ahumador_apicola',
    name: 'Ahumador Apícola de Fuelle',
    category: 'agropecuaria',
    englishQuery: 'bee smoker beekeeping tool hive inspection',
    aliases: ['ahumador', 'ahumador apicola', 'ahumador apícola', 'bee smoker', 'fuelle apicola'],
    keywordsBilingual: ['bee smoker', 'beekeeping', 'ahumador', 'apicultura', 'hive', 'smoke'],
    technicalRole: 'Generación de humo frío para calmar las colonias de abejas durante la revisión y manejo del apiario',
    safetyRule: 'Verificar que el humo sea blanco y frío (no chispas) y apagar las brasas en recipiente metálico cerrado al terminar',
    normaNOM: 'NOM-002-STPS-2010',
    familias: ['agropecuaria'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'trampa_entomologica',
    name: 'Trampa Entomológica McPhail / Cromática',
    category: 'agropecuaria',
    englishQuery: 'mcphail insect trap pest monitoring agriculture',
    aliases: ['trampa mcphail', 'trampa cromatica', 'trampa de insectos', 'trampa entomologica', 'trampa pegajosa'],
    keywordsBilingual: ['insect trap', 'mcphail', 'entomology', 'pest monitor', 'trampa'],
    technicalRole: 'Monitoreo poblacional de mosca de la fruta y plagas cuarentenarias para umbrales de manejo integrado',
    safetyRule: 'Manipular cebos alimenticios y feromonas con guantes y registrar la fecha de recambio semanal',
    normaNOM: 'NOM-075-FITO-1997',
    familias: ['agropecuaria', 'biotecnologia'],
    svgKey: 'matraz_erlenmeyer',
  },
];
