/**
 * biotecnologia.ts — Familia Tecnológica: Biotecnología y Laboratorio Ambiental
 * SIGPDA-EMS · SEMS Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const BIOTECNOLOGIA_CATALOG: CatalogItem[] = [
  {
    id: 'micropipeta_automatica',
    name: 'Micropipeta Automática Graduada (100-1000 µL)',
    category: 'laboratorio_ciencias',
    englishQuery: 'micropipette lab pipette liquid handling biotechnology',
    aliases: ['micropipeta', 'pipeta automatica', 'micropipeta variable', 'pipetman', 'micropipettor'],
    keywordsBilingual: ['micropipette', 'pipette', 'micropipeta', 'pipetman', 'aliquot', 'biotechnology'],
    technicalRole: 'Dosificación exacta y transferencia de microvolúmenes líquidos con puntas plásticas desechables estériles',
    safetyRule: 'No acostar la micropipeta con líquido en la punta y presionar suavemente hasta el primer tope para aspirar y segundo para expulsar',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['biotecnologia', 'salud', 'ciencias_experimentales'],
    svgKey: 'vernier',
  },
  {
    id: 'espectrofotometro_uv_vis',
    name: 'Espectrofotómetro UV-Visible',
    category: 'instrumento_medicion',
    englishQuery: 'spectrophotometer laboratory optical absorbance chemistry',
    aliases: ['espectrofotometro', 'espectrofotómetro', 'espectrometro', 'spectrophotometer', 'medidor de absorbancia'],
    keywordsBilingual: ['spectrophotometer', 'espectrofotometro', 'absorbance', 'wavelength', 'cuvette', 'optical density'],
    technicalRole: 'Medición de la absorbancia y transmitancia lumínica de soluciones químicas para cuantificación de concentración (Ley de Beer-Lambert)',
    safetyRule: 'Tomar las celdas o cubetas de cuarzo únicamente por las caras esmeriladas para no ensuciar la trayectoria óptica',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['biotecnologia', 'ciencias_experimentales'],
    svgKey: 'osciloscopio',
  },
  {
    id: 'centrifuga_laboratorio',
    name: 'Centrífuga Clínica de Mesa',
    category: 'laboratorio_ciencias',
    englishQuery: 'laboratory benchtop centrifuge tubes biotechnology',
    aliases: ['centrifuga', 'centrífuga', 'microcentrifuga', 'centrifuga de tubos', 'centrifuge'],
    keywordsBilingual: ['centrifuge', 'centrifuga', 'rotor', 'rpm', 'sedimentation', 'microcentrifuge'],
    technicalRole: 'Separación acelerada de fases celulares, precipitados y suspensiones mediante fuerza centrífuga relativa (RCF)',
    safetyRule: 'Equilibrar estrictamente los tubos en el rotor en posiciones diametralmente opuestas con masas idénticas antes de iniciar',
    normaNOM: 'NOM-005-STPS-1998',
    familias: ['biotecnologia', 'salud'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'microscopio_optico',
    name: 'Microscopio Óptico Binocular',
    category: 'laboratorio_ciencias',
    englishQuery: 'compound light microscope laboratory biology',
    aliases: ['microscopio', 'microscopio optico', 'microscopio compuesto', 'microscopio binocular', 'microscope'],
    keywordsBilingual: ['microscope', 'microscopio', 'lens', 'magnification', 'objective', 'slide'],
    technicalRole: 'Observación magnificada (40x a 1000x) de células, tejidos histológicos, microorganismos y protozoarios',
    safetyRule: 'Comenzar siempre el enfoque con el objetivo de menor aumento (4x) y usar aceite de inmersión únicamente con el lente 100x',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['biotecnologia', 'salud', 'ciencias_experimentales'],
    svgKey: 'microscopio',
  },
  {
    id: 'caja_petri_cultivo',
    name: 'Caja Petri Estéril con Medio de Cultivo',
    category: 'laboratorio_ciencias',
    englishQuery: 'petri dish agar plate microbiology bacterial culture',
    aliases: ['caja petri', 'placa petri', 'placa de agar', 'caja de petri', 'petri dish'],
    keywordsBilingual: ['petri dish', 'agar plate', 'caja petri', 'microbiology', 'colony', 'culture'],
    technicalRole: 'Soporte estéril para cultivo, aislamiento y recuento de colonias de bacterias y hongos en medios de agar sólido',
    safetyRule: 'Incubar siempre las placas en posición invertida para evitar que la condensación de la tapa caiga sobre las colonias',
    normaNOM: 'NOM-087-SEMARNAT-SSA1-2002',
    familias: ['biotecnologia', 'salud', 'ciencias_experimentales'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'autoclave_esterilizacion',
    name: 'Autoclave de Laboratorio para Esterilización',
    category: 'laboratorio_ciencias',
    englishQuery: 'laboratory autoclave steam sterilizer biotechnology',
    aliases: ['autoclave', 'esterilizador de vapor', 'autoclave de laboratorio', 'steam autoclave'],
    keywordsBilingual: ['autoclave', 'sterilizer', 'steam', 'esterilizacion', 'psi', 'pressure vessel'],
    technicalRole: 'Esterilización térmica por vapor de agua saturado a presión (121°C a 15 psi durante 15-20 minutos)',
    safetyRule: 'Esperar a que el manómetro descienda a 0 psi y la temperatura baje de 80°C antes de abrir la compuerta con guantes térmicos',
    normaNOM: 'NOM-020-STPS-2011',
    familias: ['biotecnologia', 'salud', 'gastronomia'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'agitador_vortex',
    name: 'Agitador Tipo Vórtex para Tubos',
    category: 'laboratorio_ciencias',
    englishQuery: 'vortex mixer laboratory test tube shaker',
    aliases: ['vortex', 'agitador vortex', 'mezclador de tubos', 'vortex mixer'],
    keywordsBilingual: ['vortex mixer', 'vortex', 'tube mixer', 'agitador', 'centrifuge tube'],
    technicalRole: 'Homogeneización rápida de suspensiones celulares y reactivos en tubos cónicos o tubos de ensayo',
    safetyRule: 'Sujetar firmemente la tapa del tubo antes de presionar el cabezal para evitar salpicaduras de reactivos',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['biotecnologia', 'ciencias_experimentales'],
    svgKey: 'matraz_erlenmeyer',
  },
];
