/**
 * ciencias-experimentales.ts — Familia: Ciencias Experimentales, Sociales y Humanidades
 * SIGPDA-EMS · DBEPA Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const CIENCIAS_EXPERIMENTALES_CATALOG: CatalogItem[] = [
  {
    id: 'matraz_erlenmeyer',
    name: 'Matraz Erlenmeyer de Borosilicato',
    category: 'laboratorio_ciencias',
    englishQuery: 'erlenmeyer flask laboratory glassware chemistry',
    aliases: ['matraz erlenmeyer', 'erlenmeyer', 'matraz conico', 'matraz cónico', 'flask'],
    keywordsBilingual: ['erlenmeyer', 'flask', 'matraz', 'borosilicate', 'titration', 'glassware'],
    technicalRole: 'Mezcla y agitación rotatoria de soluciones químicas sin riesgo de salpicaduras y calentamiento uniforme sobre tela de asbesto',
    safetyRule: 'No calentar recipientes tapados herméticamente y utilizar pinzas de madera o guantes térmicos para manipular vidrio caliente',
    normaNOM: 'NOM-018-STPS-2015',
    familias: ['ciencias_experimentales', 'biotecnologia'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'mechero_bunsen',
    name: 'Mechero Bunsen con Regulador de Aire',
    category: 'laboratorio_ciencias',
    englishQuery: 'bunsen burner laboratory flame gas burner',
    aliases: ['mechero bunsen', 'bunsen', 'mechero de gas', 'mechero de laboratorio', 'bunsen burner'],
    keywordsBilingual: ['bunsen burner', 'bunsen', 'flame', 'combustion', 'gas burner', 'llama azul'],
    technicalRole: 'Generación de calor de alta temperatura con llama no luminosa (combustión completa azul) para ebullición y esterilización',
    safetyRule: 'Abrir el collarín de aire únicamente después de encender el gas; nunca acercar frascos de disolventes volátiles o alcohol al fuego',
    normaNOM: 'NOM-005-STPS-1998',
    familias: ['ciencias_experimentales', 'biotecnologia'],
    svgKey: 'cautin',
  },
  {
    id: 'probeta_graduada',
    name: 'Probeta Graduada de Vidrio Borosilicato',
    category: 'laboratorio_ciencias',
    englishQuery: 'graduated cylinder laboratory glass volume measurement',
    aliases: ['probeta', 'probeta graduada', 'cilindro graduado', 'graduated cylinder'],
    keywordsBilingual: ['graduated cylinder', 'probeta', 'meniscus', 'volume measurement', 'milliliters'],
    technicalRole: 'Medición volumétrica directa de líquidos en mililitros (mL) con base hexagonal para estabilidad antivuelco',
    safetyRule: 'Realizar la lectura horizontal exacta a la altura del punto más bajo del menisco cóncavo del líquido',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['ciencias_experimentales', 'biotecnologia', 'agropecuaria'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'dinamometro_resorte',
    name: 'Dinamómetro de Resorte Cilíndrico',
    category: 'instrumento_medicion',
    englishQuery: 'spring balance dynamometer force meter physics',
    aliases: ['dinamometro', 'dinamómetro', 'medidor de fuerza', 'balanza de resorte', 'spring scale'],
    keywordsBilingual: ['dynamometer', 'spring balance', 'force meter', 'newton scale', 'dinamometro'],
    technicalRole: 'Medición de fuerzas mecánicas y peso en Newtons (N) basándose en la deformación elástica de un resorte (Ley de Hooke)',
    safetyRule: 'No sobrepasar la carga máxima indicada en la escala para no deformar plásticamente el resorte calibrado',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['ciencias_experimentales'],
    svgKey: 'vernier',
  },
  {
    id: 'balanza_granataria_triple',
    name: 'Balanza Granataria de Triple Brazo',
    category: 'instrumento_medicion',
    englishQuery: 'triple beam balance mechanical laboratory scale physics',
    aliases: ['balanza granataria', 'balanza de triple brazo', 'granataria', 'triple beam balance'],
    keywordsBilingual: ['triple beam balance', 'balanza granataria', 'tare', 'mass measurement', 'fulcrum'],
    technicalRole: 'Determinación precisa de la masa de reactivos y muestras sólidas con sensibilidad de 0.1 g o 0.01 g',
    safetyRule: 'Ajustar el tornillo de cero antes de pesar y mover las pesas correderas hasta que el fiel coincida con la marca cero',
    normaNOM: 'NOM-010-SCFI-1994',
    familias: ['ciencias_experimentales', 'biotecnologia'],
    svgKey: 'vernier',
  },
  {
    id: 'soporte_universal_pinzas',
    name: 'Soporte Universal de Hierro con Pinzas y Nuez',
    category: 'laboratorio_ciencias',
    englishQuery: 'laboratory retort stand iron ring clamp chemistry',
    aliases: ['soporte universal', 'pie universal', 'soporte de laboratorio', 'retort stand', 'pinza con nuez'],
    keywordsBilingual: ['retort stand', 'ring stand', 'soporte universal', 'clamp', 'laboratory hardware'],
    technicalRole: 'Armado de sistemas experimentales verticales: destilaciones, filtraciones y sostenimiento de buretas y matraces',
    safetyRule: 'Orientar la base pesada de hierro hacia el frente del montaje para mantener bajo el centro de gravedad',
    normaNOM: 'NOM-018-STPS-2015',
    familias: ['ciencias_experimentales'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'tubo_ensayo_gradilla',
    name: 'Tubos de Ensayo con Gradilla',
    category: 'laboratorio_ciencias',
    englishQuery: 'test tubes with rack laboratory chemistry',
    aliases: ['tubo de ensayo', 'tubos de ensayo', 'gradilla', 'test tube', 'tubo borosilicato'],
    keywordsBilingual: ['test tube', 'test tube rack', 'tubo ensayo', 'gradilla', 'reaction tube'],
    technicalRole: 'Contención de muestras de pequeña escala para reacciones colorimétricas, precipitaciones y calentamiento breve',
    safetyRule: 'Al calentar un tubo de ensayo con pinzas, apuntar siempre la boca del tubo hacia una pared vacía, nunca hacia personas',
    normaNOM: 'NOM-018-STPS-2015',
    familias: ['ciencias_experimentales', 'biotecnologia'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'calculadora_cientifica_pantalla',
    name: 'Calculadora Científica / Financiera de Pantalla Natural',
    category: 'dibujo_matematicas',
    englishQuery: 'scientific calculator natural display mathematics physics',
    aliases: ['calculadora cientifica', 'calculadora científica', 'calculadora financiera', 'scientific calculator'],
    keywordsBilingual: ['scientific calculator', 'calculator', 'calculadora', 'matrix', 'trigonometry', 'statistics'],
    technicalRole: 'Cálculo de funciones trigonométricas, matrices, desviaciones estadísticas y regresiones matemáticas',
    safetyRule: 'Verificar el modo angular de trabajo (grados DEG, radianes RAD o gradianes GRA) antes de evaluar funciones trigonométricas',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['ciencias_experimentales', 'diseno_grafico'],
    svgKey: 'multimetro',
  },
  {
    id: 'cinta_metrica_agrimensor',
    name: 'Cinta Métrica de Agrimensor / Odómetro Topográfico',
    category: 'instrumento_medicion',
    englishQuery: 'surveyor tape measure measuring wheel surveying geography',
    aliases: ['cinta de agrimensor', 'cinta metrica de 50m', 'odometro', 'odómetro', 'rueda de medicion', 'surveyor tape'],
    keywordsBilingual: ['measuring wheel', 'surveyor tape', 'odometer', 'cinta agrimensor', 'topography', 'distance survey'],
    technicalRole: 'Medición de distancias territoriales de 30 a 100 metros en levantamientos comunitarios y proyectos PAEC',
    safetyRule: 'Tensar la cinta de fibra de vidrio sin torsionar la cinta para no alterar la precisión por catenaria',
    normaNOM: 'NOM-046-SCFI-1999',
    familias: ['ciencias_experimentales', 'agropecuaria'],
    svgKey: 'vernier',
  },
  {
    id: 'globo_terraqueo_inclinado',
    name: 'Globo Terráqueo Físico-Político con Eje de 23.5°',
    category: 'dibujo_matematicas',
    englishQuery: 'terrestrial globe physical political world geography',
    aliases: ['globo terraqueo', 'globo terráqueo', 'globo del mundo', 'terrestrial globe', 'esfera terrestre'],
    keywordsBilingual: ['globe', 'terrestrial globe', 'globo terraqueo', 'latitude', 'longitude', 'equator', 'geography'],
    technicalRole: 'Modelado tridimensional de coordenadas geográficas (latitud, longitud), zonas horarias y estaciones del año',
    safetyRule: 'Girar sobre el meridiano de soporte sin forzar el pivote polar para evitar desalineación del eje de rotación',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['ciencias_experimentales'],
    svgKey: 'compas_precision',
  },
  {
    id: 'reloj_checador_biometrico',
    name: 'Reloj Checador Biométrico de Huella Digital',
    category: 'tecnologia_computo',
    englishQuery: 'biometric time clock fingerprint attendance office',
    aliases: ['reloj checador', 'checador biometrico', 'control de asistencia', 'time clock', 'lector de huella'],
    keywordsBilingual: ['time clock', 'biometric', 'reloj checador', 'fingerprint reader', 'attendance', 'clock in'],
    technicalRole: 'Registro automatizado de asistencia laboral y cálculo de jornadas en módulos de Administración de Recursos Humanos',
    safetyRule: 'Limpiar el prisma óptico de lectura con toalla de microfibra sin alcoholes abrasivos que degraden el sensor',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['ciencias_experimentales', 'tics_ciberseguridad'],
    svgKey: 'multimetro',
  },
];
