/**
 * diseno-grafico.ts — Familia Tecnológica: Diseño Gráfico, Dibujo Técnico y Construcción
 * SIGPDA-EMS · SEMS Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const DISENO_GRAFICO_CATALOG: CatalogItem[] = [
  {
    id: 'escalimetro_triangular',
    name: 'Escalímetro Triangular de Precisión',
    category: 'dibujo_matematicas',
    englishQuery: 'architect triangular scale ruler technical drafting',
    aliases: ['escalimetro', 'escalímetro', 'regla de escalas', 'triangular scale', 'escalimetro de arquitecto'],
    keywordsBilingual: ['scale ruler', 'architect scale', 'escalimetro', 'drafting', 'ratio scale', 'blueprint'],
    technicalRole: 'Lectura y trazado directo de planos a escalas normalizadas (1:20, 1:25, 1:50, 1:75, 1:100, 1:125) sin conversión matemática',
    safetyRule: 'No utilizar los bordes de plástico del escalímetro como guía para corte con navaja o cúter',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['diseno_grafico', 'ciencias_experimentales'],
    svgKey: 'vernier',
  },
  {
    id: 'compas_precision_bigotera',
    name: 'Compás de Precisión con Bigotera Micrométrica',
    category: 'dibujo_matematicas',
    englishQuery: 'precision drafting compass bow technical drawing',
    aliases: ['compas', 'compás', 'compas de precision', 'bigotera', 'compas con bigotera', 'drafting compass'],
    keywordsBilingual: ['compass', 'drafting compass', 'compas', 'arc', 'circle drawing', 'precision bow'],
    technicalRole: 'Trazado exacto de circunferencias y arcos técnicos manteniendo la apertura fija mediante tornillo de ajuste central',
    safetyRule: 'Mantener la aguja de acero afilada y guardarlo con las patas cerradas en su estuche rígido para no doblar puntas',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['diseno_grafico', 'ciencias_experimentales'],
    svgKey: 'compas_precision',
  },
  {
    id: 'regla_t_dibujo',
    name: 'Regla T de Acrílico para Tablero de Dibujo',
    category: 'dibujo_matematicas',
    englishQuery: 't square ruler acrylic drafting technical drawing',
    aliases: ['regla t', 'regla te', 't square', 'regla t de dibujo'],
    keywordsBilingual: ['t square', 't-square', 'regla t', 'drafting board', 'parallel line'],
    technicalRole: 'Guía de apoyo perpendicular sobre el canto de la mesa para el trazado de líneas horizontales y base para escuadras',
    safetyRule: 'Verificar la solidez de los tornillos de la cabeza de la regla T para garantizar ángulo recto de 90° exacto',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['diseno_grafico'],
    svgKey: 'compas_precision',
  },
  {
    id: 'juego_escuadras_tecnicas',
    name: 'Juego de Escuadras Técnicas (45° y 30°/60°)',
    category: 'dibujo_matematicas',
    englishQuery: 'set squares drafting triangles technical drawing 45 60',
    aliases: ['escuadras', 'juego de escuadras', 'cartabon', 'cartabón', 'set squares'],
    keywordsBilingual: ['set square', 'drafting triangle', 'escuadra', 'cartabon', 'angles drafting'],
    technicalRole: 'Trazado de ángulos estándar y paralelas en combinación sobre la regla T para proyecciones isométricas',
    safetyRule: 'Limpiar los cantos con paño suave para no arrastrar grafito ni rayar el papel mantequilla o albaneve',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['diseno_grafico', 'ciencias_experimentales'],
    svgKey: 'compas_precision',
  },
  {
    id: 'tableta_digitalizadora',
    name: 'Tableta Gráfica Digitalizadora con Lápiz Stylus',
    category: 'tecnologia_computo',
    englishQuery: 'graphic drawing tablet stylus digital art illustration',
    aliases: ['tableta grafica', 'tableta digitalizadora', 'drawing tablet', 'pen tablet', 'tableta de dibujo'],
    keywordsBilingual: ['drawing tablet', 'graphics tablet', 'stylus', 'pressure sensitivity', 'digital illustration'],
    technicalRole: 'Entrada digital precisa con 8192 niveles de presión e inclinación para ilustración vectorial y retoque fotográfico',
    safetyRule: 'Evitar caídas del lápiz óptico electromagnético para prevenir rotura de la bobina interna de resonancia',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['diseno_grafico', 'tics_ciberseguridad'],
    svgKey: 'osciloscopio',
  },
  {
    id: 'flexometro_cinta_seguro',
    name: 'Flexómetro de Cinta Metálica con Seguro',
    category: 'instrumento_medicion',
    englishQuery: 'tape measure metal measuring tape construction tool',
    aliases: ['flexometro', 'flexómetro', 'cinta metrica', 'metro de cinta', 'tape measure'],
    keywordsBilingual: ['tape measure', 'measuring tape', 'flexometro', 'metric tape', 'dimension'],
    technicalRole: 'Medición rápida de longitudes y dimensiones arquitectónicas con gancho móvil autorregulable de cero absoluto',
    safetyRule: 'Controlar el retroceso de la cinta con el dedo índice para evitar cortes metálicos en la mano al enrollar',
    normaNOM: 'NOM-046-SCFI-1999',
    familias: ['diseno_grafico', 'electricidad_energia'],
    svgKey: 'vernier',
  },
];
