/**
 * electricidad-energia.ts — Familia Tecnológica: Electricidad, Energía y Mantenimiento Industrial
 * SIGPDA-EMS · DBEPA Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const ELECTRICIDAD_ENERGIA_CATALOG: CatalogItem[] = [
  {
    id: 'amperimetro_gancho',
    name: 'Amperímetro de Gancho (Pinza Amperimétrica)',
    category: 'instrumento_medicion',
    englishQuery: 'clamp meter digital current clamp electrical',
    aliases: ['amperimetro de gancho', 'pinza amperimetrica', 'clamp meter', 'gancho amperimetrico', 'amperímetro de gancho', 'pinza amperimétrica'],
    keywordsBilingual: ['clamp meter', 'amperimetro', 'current clamp', 'amperage', 'ac current', 'dc current'],
    technicalRole: 'Medición no invasiva de corriente alterna y directa en conductores energizados mediante inducción electromagnética',
    safetyRule: 'Abrazar un solo conductor de fase a la vez; nunca rodear conductores de fase y neutro juntos en el gancho',
    normaNOM: 'NOM-001-SEDE-2012',
    familias: ['electricidad_energia', 'electronica_mecatronica'],
    svgKey: 'amperimetro_gancho',
  },
  {
    id: 'calibrador_vernier',
    name: 'Calibrador Vernier (Pie de Rey)',
    category: 'instrumento_medicion',
    englishQuery: 'vernier caliper measuring tool precision',
    aliases: ['calibrador vernier', 'vernier', 'pie de rey', 'calibrador pie de rey', 'caliper digital'],
    keywordsBilingual: ['vernier', 'caliper', 'calibrador', 'precision measurement', 'micrometer'],
    technicalRole: 'Medición precisa de dimensiones exteriores, interiores y profundidades con resolución de 0.02 mm o 0.001 pulg',
    safetyRule: 'Verificar el ajuste en cero con mordazas limpias y no aplicar fuerza excesiva en el rodillo de avance',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['electricidad_energia', 'ciencias_experimentales'],
    svgKey: 'vernier',
  },
  {
    id: 'micrometro_exteriores',
    name: 'Micrómetro de Exteriores (Palmer)',
    category: 'instrumento_medicion',
    englishQuery: 'micrometer screw gauge precision engineering',
    aliases: ['micrometro', 'micrómetro', 'tornillo micrometrico', 'palmer', 'micrometro de exteriores'],
    keywordsBilingual: ['micrometer', 'micrometro', 'screw gauge', 'precision', 'spindle'],
    technicalRole: 'Medición de espesores y diámetros exteriores de piezas maquinadas con resolución micrométrica (0.001 mm)',
    safetyRule: 'Girar siempre con la perilla de trinquete para garantizar la presión de medición uniforme sin dañar la rosca patrón',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['electricidad_energia'],
    svgKey: 'vernier',
  },
  {
    id: 'torquimetro_dinamometrica',
    name: 'Torquímetro (Llave Dinamométrica)',
    category: 'herramienta_taller',
    englishQuery: 'torque wrench mechanical tightening',
    aliases: ['torquimetro', 'torquímetro', 'llave dinamometrica', 'torque wrench', 'matraca dinamometrica'],
    keywordsBilingual: ['torque wrench', 'torquimetro', 'tightening', 'ft-lb', 'nm', 'torque'],
    technicalRole: 'Aplicación de par de apriete exacto (en N·m o lb·ft) según especificaciones de fabricante en tornillos y pernos',
    safetyRule: 'Detener la fuerza inmediatamente al escuchar el "clic" audible y liberar el resorte a cero al terminar de usarlo',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['electricidad_energia'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'manometro_manifold',
    name: 'Juego de Manómetros para Refrigeración (Manifold)',
    category: 'instrumento_medicion',
    englishQuery: 'refrigeration manifold gauge hvac service',
    aliases: ['manifold', 'manometros de refrigeracion', 'juego de manometros', 'manometro manifold', 'puente de manometros'],
    keywordsBilingual: ['manifold', 'refrigeration gauge', 'hvac', 'pressure gauge', 'freon', 'psi'],
    technicalRole: 'Medición simultánea de presiones de succión (baja) y descarga (alta) y carga de refrigerante en sistemas HVAC',
    safetyRule: 'Purgar mangueras antes de conectar y utilizar gafas de protección facial completa contra quemaduras criogénicas de refrigerante',
    normaNOM: 'NOM-005-STPS-1998',
    familias: ['electricidad_energia'],
    svgKey: 'amperimetro_gancho',
  },
  {
    id: 'megohmetro_aislamiento',
    name: 'Megóhmetro (Probador de Aislamiento / Megger)',
    category: 'instrumento_medicion',
    englishQuery: 'insulation resistance tester megohmmeter megger',
    aliases: ['megometro', 'megohmetro', 'megóhmetro', 'megger', 'probador de aislamiento'],
    keywordsBilingual: ['megohmmeter', 'insulation tester', 'megger', 'high voltage', 'resistance'],
    technicalRole: 'Prueba de rigidez dieléctrica y resistencia de aislamiento en devanados de motores y cables con tensiones de prueba de 250V a 1000V',
    safetyRule: 'Asegurar circuito completamente desenergizado y descargar capacitancias residuales a tierra antes de tocar terminales',
    normaNOM: 'NOM-029-STPS-2011',
    familias: ['electricidad_energia'],
    svgKey: 'multimetro',
  },
  {
    id: 'detector_tension_lapiz',
    name: 'Detector de Tensión sin Contacto (Lápiz Buscapolos)',
    category: 'seguridad_epp',
    englishQuery: 'non contact voltage tester pen electrical safety',
    aliases: ['detector de voltaje', 'lapiz detector', 'detector de tension', 'buscapolos inductivo', 'voltage detector'],
    keywordsBilingual: ['voltage tester', 'voltage detector', 'detector tension', 'live wire', 'non-contact'],
    technicalRole: 'Comprobación preliminar de presencia de campo eléctrico en conductores y contactos sin pelar el cable',
    safetyRule: 'Probar el detector en una fuente energizada conocida antes y después de cada medición de comprobación',
    normaNOM: 'NOM-029-STPS-2011',
    familias: ['electricidad_energia', 'electronica_mecatronica'],
    svgKey: 'multimetro',
  },
  {
    id: 'tacometro_digital',
    name: 'Tacómetro Digital Láser / Contacto',
    category: 'instrumento_medicion',
    englishQuery: 'digital tachometer rpm meter laser non contact',
    aliases: ['tacometro', 'tacómetro', 'tacometro digital', 'rpm meter', 'medidor de rpm'],
    keywordsBilingual: ['tachometer', 'tacometro', 'rpm', 'rotation', 'speed meter'],
    technicalRole: 'Medición de velocidad rotacional angular en flechas, poleas y motores en revoluciones por minuto (RPM)',
    safetyRule: 'Mantener distancia de seguridad respecto a partes mecánicas en movimiento rotativo y colocar cinta reflejante limpia',
    normaNOM: 'NOM-004-STPS-1999',
    familias: ['electricidad_energia'],
    svgKey: 'amperimetro_gancho',
  },
  {
    id: 'interruptor_termomagnetico',
    name: 'Interruptor Termomagnético (Pastilla Térmica)',
    category: 'herramienta_taller',
    englishQuery: 'miniature circuit breaker mcb electrical panel',
    aliases: ['pastilla termica', 'interruptor termomagnetico', 'termomagnetico', 'breaker', 'disyuntor', 'pastilla termomagnetica'],
    keywordsBilingual: ['circuit breaker', 'termomagnetico', 'breaker', 'overcurrent', 'mcb'],
    technicalRole: 'Protección contra sobrecargas térmicas y cortocircuitos magnéticos en tableros de distribución eléctrica',
    safetyRule: 'Seleccionar la capacidad nominal en amperios (15A, 20A, 30A) según el calibre del conductor (14, 12, 10 AWG)',
    normaNOM: 'NOM-001-SEDE-2012',
    familias: ['electricidad_energia'],
    svgKey: 'multimetro',
  },
  {
    id: 'guantes_dielectricos',
    name: 'Guantes Dieléctricos con Guantelete de Cuero',
    category: 'seguridad_epp',
    englishQuery: 'electrical insulating rubber gloves high voltage safety',
    aliases: ['guantes dielectricos', 'guantes dieléctricos', 'guantes de electricista', 'guantes aislantes'],
    keywordsBilingual: ['insulating gloves', 'guantes dielectricos', 'rubber gloves', 'electrical safety', 'class 0'],
    technicalRole: 'Protección personal de manos y antebrazos contra descargas eléctricas y contacto accidental con conductores vivos',
    safetyRule: 'Inspeccionar inflado de aire para detectar micro-perforaciones antes de cada uso y usar sobreguante de cuero protector',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['electricidad_energia'],
    svgKey: 'herramienta_generica',
  },
];
