/**
 * electronica-mecatronica.ts — Familia Tecnológica: Electrónica, Mecatrónica y Domótica
 * SIGPDA-EMS · DBEPA Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const ELECTRONICA_MECATRONICA_CATALOG: CatalogItem[] = [
  {
    id: 'multimetro',
    name: 'Multímetro Digital',
    category: 'instrumento_medicion',
    englishQuery: 'digital multimeter electrical testing',
    aliases: ['multimetro', 'multimetro digital', 'polimetro', 'tester', 'multímetro', 'multímetro digital', 'polímetro'],
    keywordsBilingual: ['multimeter', 'multimetro', 'meter', 'tester', 'voltmeter', 'ammeter'],
    technicalRole: 'Medición de voltaje (V), corriente (A), resistencia (Ω) y prueba de continuidad en circuitos',
    safetyRule: 'Verificar categoría de aislamiento CAT III/IV y verificar cero tensión antes de medir resistencia',
    normaNOM: 'NOM-001-SEDE-2012',
    familias: ['electronica_mecatronica', 'electricidad_energia'],
    svgKey: 'multimetro',
  },
  {
    id: 'osciloscopio',
    name: 'Osciloscopio Digital',
    category: 'instrumento_medicion',
    englishQuery: 'digital oscilloscope waveform display electronics',
    aliases: ['osciloscopio', 'osciloscopio digital', 'scope', 'osciloscopio de almacenamiento digital', 'dso'],
    keywordsBilingual: ['oscilloscope', 'osciloscopio', 'waveform', 'signal', 'voltage', 'frequency'],
    technicalRole: 'Visualización y análisis temporal de formas de onda, frecuencia, amplitud y señales digitales',
    safetyRule: 'Conectar la referencia a tierra física del circuito para evitar cortocircuitos por la sonda',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['electronica_mecatronica'],
    svgKey: 'osciloscopio',
  },
  {
    id: 'generador_funciones',
    name: 'Generador de Funciones / Señales',
    category: 'instrumento_medicion',
    englishQuery: 'function generator waveform signal generator',
    aliases: ['generador de funciones', 'generador de senales', 'generador de señales', 'signal generator'],
    keywordsBilingual: ['function generator', 'signal generator', 'waveform', 'frecuencia', 'frequency', 'sine wave'],
    technicalRole: 'Generación de señales senoidales, cuadradas y triangulares para prueba de circuitos y filtros',
    safetyRule: 'Ajustar la amplitud y el offset de CD antes de conectar a componentes semiconductores sensibles',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['electronica_mecatronica'],
    svgKey: 'osciloscopio',
  },
  {
    id: 'cautin_estacion',
    name: 'Cautín de Estación para Soldar',
    category: 'herramienta_taller',
    englishQuery: 'soldering iron station electronics rework',
    aliases: ['cautin', 'cautín', 'estacion de soldar', 'estación de soldar', 'soldador tipo lapiz', 'soldador'],
    keywordsBilingual: ['soldering', 'solder', 'cautin', 'iron', 'welding', 'tin'],
    technicalRole: 'Unión permanente de componentes electrónicos mediante soldadura de estaño/plomo o lead-free',
    safetyRule: 'Trabajar en área ventilada con extractor de humo, usar soporte térmico y gafas de protección',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['electronica_mecatronica'],
    svgKey: 'cautin',
  },
  {
    id: 'protoboard',
    name: 'Placa de Pruebas (Protoboard)',
    category: 'herramienta_taller',
    englishQuery: 'breadboard electronics prototyping board',
    aliases: ['protoboard', 'placa de pruebas', 'tablilla de experimentos', 'breadboard', 'proto'],
    keywordsBilingual: ['breadboard', 'protoboard', 'prototyping', 'circuit', 'jumper'],
    technicalRole: 'Montaje rápido de circuitos electrónicos experimentales sin necesidad de soldadura',
    safetyRule: 'Desconectar la fuente de alimentación antes de insertar o reconfigurar cables y componentes',
    normaNOM: 'NOM-001-SEDE-2012',
    familias: ['electronica_mecatronica', 'tics_ciberseguridad'],
    svgKey: 'protoboard',
  },
  {
    id: 'fuente_cd_regulable',
    name: 'Fuente de Alimentación CD Regulable',
    category: 'instrumento_medicion',
    englishQuery: 'bench power supply dc variable lab power supply',
    aliases: ['fuente de poder', 'fuente de alimentacion', 'fuente regulada', 'power supply', 'fuente de laboratorio'],
    keywordsBilingual: ['power supply', 'dc supply', 'voltage regulator', 'fuente'],
    technicalRole: 'Suministro de voltaje y corriente directa regulada con limitador de corriente para pruebas seguras',
    safetyRule: 'Ajustar la limitación de corriente antes de energizar prototipos para evitar sobrecalentamiento',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['electronica_mecatronica', 'electricidad_energia'],
    svgKey: 'osciloscopio',
  },
  {
    id: 'pinzas_pelacable',
    name: 'Pinzas Pelacables de Precisión',
    category: 'herramienta_taller',
    englishQuery: 'wire stripper pliers electronics precision',
    aliases: ['pelacables', 'pelacable', 'pinza pelacable', 'wire stripper', 'desforradora'],
    keywordsBilingual: ['wire stripper', 'stripper', 'pliers', 'pelacables', 'cables'],
    technicalRole: 'Retiro del aislante plástico en conductores de calibres 20 a 30 AWG sin dañar el núcleo de cobre',
    safetyRule: 'Seleccionar el orificio con el calibre exacto del conductor para evitar muescas en el cobre',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['electronica_mecatronica', 'electricidad_energia', 'tics_ciberseguridad'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'desoldador_succion',
    name: 'Extractor de Soldadura por Succión',
    category: 'herramienta_taller',
    englishQuery: 'desoldering pump solder sucker',
    aliases: ['desoldador', 'extractor de soldadura', 'bomba de desoldar', 'solder sucker'],
    keywordsBilingual: ['desoldering', 'sucker', 'pump', 'desoldador', 'soldering'],
    technicalRole: 'Remoción de estaño fundido en terminales de componentes electrónicos para desmontaje y reparación',
    safetyRule: 'Limpiar periódicamente la cámara interna de residuos de estaño para evitar atascos y quemaduras',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['electronica_mecatronica'],
    svgKey: 'cautin',
  },
  {
    id: 'arduino_microcontrolador',
    name: 'Módulo Microcontrolador (Arduino / ESP32)',
    category: 'tecnologia_computo',
    englishQuery: 'arduino uno microcontroller board development',
    aliases: ['arduino', 'arduino uno', 'esp32', 'microcontrolador', 'placa de desarrollo', 'atmega328p'],
    keywordsBilingual: ['arduino', 'microcontroller', 'esp32', 'atmega', 'development board'],
    technicalRole: 'Control programable de sensores, actuadores, relevadores y adquisición de señales digitales y analógicas',
    safetyRule: 'No exceder los 5V y 40mA por pin de entrada/salida para no dañar el circuito integrado',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['electronica_mecatronica', 'tics_ciberseguridad'],
    svgKey: 'arduino',
  },
  {
    id: 'servomotor_actuador',
    name: 'Servomotor de Posición Angular',
    category: 'herramienta_taller',
    englishQuery: 'rc servo motor mechatronics robotics',
    aliases: ['servomotor', 'servo', 'motor de pasos', 'stepper motor', 'actuador mecatronico'],
    keywordsBilingual: ['servo', 'servomotor', 'stepper', 'motor', 'actuator', 'robotics'],
    technicalRole: 'Posicionamiento angular preciso (0° a 180°) en mecanismos robóticos y automatización mecatrónica',
    safetyRule: 'Alimentar los servomotores con línea de energía independiente al microcontrolador para evitar caídas de tensión',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['electronica_mecatronica'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'pulsera_antiestatica',
    name: 'Pulsera Antiestática ESD',
    category: 'seguridad_epp',
    englishQuery: 'anti static wrist strap esd protection electronics',
    aliases: ['pulsera antiestatica', 'pulsera esd', 'brazalete antiestatico', 'correa esd'],
    keywordsBilingual: ['wrist strap', 'anti-static', 'esd', 'antiestatica', 'grounding'],
    technicalRole: 'Disipación de cargas electrostáticas del cuerpo del operador antes de manipular circuitos integrados MOS',
    safetyRule: 'Asegurar conexión a tierra mediante el cable con resistencia integrada de 1 MΩ para protección del usuario',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['electronica_mecatronica', 'tics_ciberseguridad'],
    svgKey: 'herramienta_generica',
  },
];
