/**
 * gastronomia.ts — Familia Tecnológica: Gastronomía, Alimentos, Turismo y Servicios
 * SIGPDA-EMS · SEMS Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const GASTRONOMIA_CATALOG: CatalogItem[] = [
  // ── Alimentos y Bebidas ─────────────────────────────────────────────────────
  {
    id: 'termometro_alimentos_sonda',
    name: 'Termómetro de Sonda / Inmersión para Alimentos',
    category: 'alimentos_gastronomia',
    englishQuery: 'digital food probe thermometer culinary safety haccp',
    aliases: ['termometro de alimentos', 'termometro de cocina', 'termometro de sonda', 'food thermometer', 'termómetro de alimentos'],
    keywordsBilingual: ['food thermometer', 'probe thermometer', 'termometro alimentos', 'cooking temperature', 'haccp', 'internal temp'],
    technicalRole: 'Verificación de temperaturas críticas de cocción (aves ≥74°C, carnes ≥68°C) y zona de peligro de temperatura (4°C a 60°C)',
    safetyRule: 'Desinfectar la sonda de acero inoxidable con toallita con alcohol o solución clorada antes y después de insertarla en el alimento',
    normaNOM: 'NOM-251-SSA1-2009',
    familias: ['gastronomia'],
    svgKey: 'amperimetro_gancho',
  },
  {
    id: 'bascula_gramera_digital',
    name: 'Báscula Gramera Digital de Cocina',
    category: 'instrumento_medicion',
    englishQuery: 'digital kitchen scale precision grams culinary',
    aliases: ['bascula gramera', 'báscula gramera', 'balanza de cocina', 'gramera', 'kitchen scale'],
    keywordsBilingual: ['kitchen scale', 'digital scale', 'gramera', 'tara', 'weight grams', 'culinary'],
    technicalRole: 'Pesaje exacto de ingredientes secos y líquidos con función de tara para estandarización de recetas y rendimiento',
    safetyRule: 'Colocar sobre superficie rígida nivelada y usar recipientes secos para no mojar la celda de carga electrónica',
    normaNOM: 'NOM-010-SCFI-1994',
    familias: ['gastronomia', 'agropecuaria'],
    svgKey: 'vernier',
  },
  {
    id: 'cuchillo_chef_haccp',
    name: 'Cuchillo de Chef Profesional con Código de Color HACCP',
    category: 'herramienta_taller',
    englishQuery: 'chef knife stainless steel cutting board culinary',
    aliases: ['cuchillo de chef', 'cuchillo cocinero', 'cuchillo cebollero', 'chef knife', 'cuchillo profesional'],
    keywordsBilingual: ['chef knife', 'cuchillo chef', 'haccp', 'blade', 'cutting board', 'santoku'],
    technicalRole: 'Cortes técnicos fundamentales (juliana, brunoise, macedonia, chiffonade) con tabla de corte codificada por color',
    safetyRule: 'Usar técnica de garra con los nudillos protegiendo las yemas de los dedos y apoyar la tabla sobre paño antideslizante',
    normaNOM: 'NOM-251-SSA1-2009',
    familias: ['gastronomia'],
    svgKey: 'cautin',
  },
  {
    id: 'mandolina_cocina',
    name: 'Mandolina de Cocina Profesional de Acero',
    category: 'herramienta_taller',
    englishQuery: 'mandoline slicer vegetable stainless steel culinary',
    aliases: ['mandolina', 'mandolina de cocina', 'rebanadora manual', 'mandoline slicer'],
    keywordsBilingual: ['mandoline', 'mandolina', 'slicer', 'julienne blade', 'vegetable slice'],
    technicalRole: 'Rebanado y corte uniforme y veloz de verduras en láminas milimétricas, gofrado y tiras de corte regular',
    safetyRule: 'Utilizar OBLIGATORIAMENTE el carro protector o guante de malla metálica anticorte al empujar los vegetales',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['gastronomia'],
    svgKey: 'vernier',
  },
  {
    id: 'batidor_globo_acero',
    name: 'Batidor de Globo Francés de Alambre de Acero',
    category: 'herramienta_taller',
    englishQuery: 'wire whisk balloon whisk culinary baking',
    aliases: ['batidor de globo', 'batidor de alambre', 'whisk', 'batidor frances'],
    keywordsBilingual: ['wire whisk', 'whisk', 'batidor globo', 'emulsion', 'whipping'],
    technicalRole: 'Incorporación de aire en emulsiones (mayonesas, vinagretas), merengues y batido de cremas',
    safetyRule: 'Verificar la sujeción de los alambres al mango para evitar desprendimientos metálicos dentro del alimento preparado',
    normaNOM: 'NOM-251-SSA1-2009',
    familias: ['gastronomia'],
    svgKey: 'herramienta_generica',
  },

  // ── Turismo, Hospedaje y Servicios Recreativos ─────────────────────────────
  {
    id: 'radio_vhf_walkie_talkie',
    name: 'Radio Transceptor Portátil VHF/UHF (Walkie-Talkie)',
    category: 'tecnologia_computo',
    englishQuery: 'two way radio walkie talkie vhf uhf transceiver hospitality',
    aliases: ['walkie talkie', 'radio transmisor', 'radio vhf', 'transceptor portatil', 'radio de dos vias'],
    keywordsBilingual: ['two-way radio', 'walkie talkie', 'vhf radio', 'transceiver', 'push to talk', 'channel'],
    technicalRole: 'Comunicación de coordinación operativa inmediata entre áreas de servicio, recepción, camaristas y guías de grupo',
    safetyRule: 'Mantener canal de emergencia reservado y verificar carga completa de la batería de litio antes del recorrido',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['servicios_turismo', 'gastronomia'],
    svgKey: 'multimetro',
  },
  {
    id: 'cerradura_tarjeta_rfid',
    name: 'Cerradura Electrónica y Lector de Tarjeta RFID',
    category: 'tecnologia_computo',
    englishQuery: 'hotel rfid door lock key card reader hospitality',
    aliases: ['tarjeta rfid', 'cerradura rfid', 'llave magnetica', 'lector rfid', 'tarjeta de proximidad'],
    keywordsBilingual: ['rfid lock', 'key card', 'card reader', 'rfid', 'hotel door lock', 'contactless'],
    technicalRole: 'Control de accesos seguro y codificación de credenciales de huésped por radiofrecuencia (13.56 MHz)',
    safetyRule: 'No exponer las tarjetas magnéticas ni el codificador a campos magnéticos intensos para evitar desprogramación',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['servicios_turismo'],
    svgKey: 'multimetro',
  },
  {
    id: 'chaleco_salvavidas',
    name: 'Chaleco Salvavidas Reglamentario de Alta Flotabilidad',
    category: 'seguridad_epp',
    englishQuery: 'life jacket life vest marine safety water sports',
    aliases: ['chaleco salvavidas', 'salvavidas', 'chaleco de flotacion', 'life jacket', 'chaleco nautico'],
    keywordsBilingual: ['life jacket', 'life vest', 'chaleco salvavidas', 'buoyancy', 'marine safety', 'pfd'],
    technicalRole: 'Dispositivo individual de flotabilidad reglamentario para actividades acuáticas, ecoturismo y transporte fluvial',
    safetyRule: 'Ajustar todas las cintas de torso y entrepierna con firmeza y verificar silbato de emergencia integrado',
    normaNOM: 'NOM-006-SCT4-2015',
    familias: ['servicios_turismo'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'botiquin_primeros_auxilios',
    name: 'Botiquín de Primeros Auxilios Portátil de Maletín',
    category: 'seguridad_epp',
    englishQuery: 'first aid kit emergency medical kit tourism safety',
    aliases: ['botiquin', 'botiquín', 'botiquin de primeros auxilios', 'maletin de primeros auxilios', 'first aid kit'],
    keywordsBilingual: ['first aid kit', 'botiquin', 'emergency kit', 'gauze', 'antiseptic', 'bandage'],
    technicalRole: 'Atención prehospitalaria inmediata de contusiones, heridas, quemaduras leves y picaduras en excursiones y establecimientos',
    safetyRule: 'Revisar mensualmente fechas de caducidad de apósitos y antisépticos y reponer material utilizado inmediatamente',
    normaNOM: 'NOM-005-STPS-1998',
    familias: ['servicios_turismo', 'salud'],
    svgKey: 'matraz_erlenmeyer',
  },
  {
    id: 'brujula_orientacion',
    name: 'Brújula Cartográfica de Orientación Terrestre',
    category: 'instrumento_medicion',
    englishQuery: 'orienteering compass map reading outdoor navigation',
    aliases: ['brujula', 'brújula', 'brujula cartografica', 'brujula de orientacion', 'orienteering compass'],
    keywordsBilingual: ['compass', 'orienteering', 'brujula', 'magnetic north', 'azimuth', 'bearing'],
    technicalRole: 'Determinación de rumbos, acimuts magnéticos y triangulación sobre cartas topográficas en senderismo y ecoturismo',
    safetyRule: 'Alejar la aguja magnética al menos 1 metro de objetos ferrosos, teléfonos móviles y líneas de alta tensión al medir',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['servicios_turismo', 'ciencias_experimentales'],
    svgKey: 'compas_precision',
  },
  {
    id: 'gps_navegador_mano',
    name: 'Navegador Satelital GPS de Mano para Ecoturismo',
    category: 'tecnologia_computo',
    englishQuery: 'handheld gps navigator satellite outdoor mapping',
    aliases: ['gps', 'gps de mano', 'navegador satelital', 'gps portatil', 'handheld gps'],
    keywordsBilingual: ['handheld gps', 'satellite navigator', 'waypoints', 'coordinates', 'latitude', 'longitude'],
    technicalRole: 'Georreferenciación de rutas, waypoints y coordenadas UTM en recorridos turísticos y delimitación de senderos',
    safetyRule: 'Calibrar la brújula electrónica en campo abierto y respaldar los tracks con batería externa de reserva',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['servicios_turismo'],
    svgKey: 'multimetro',
  },
];
