/**
 * mecanica-soldadura.ts — Familia Tecnológica: Mecánica, Soldadura y Manufactura
 * SIGPDA-EMS · DBEPA Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const MECANICA_SOLDADURA_CATALOG: CatalogItem[] = [
  {
    id: 'careta_soldar_fotosensible',
    name: 'Careta Electrónica Fotosensible para Soldar',
    category: 'seguridad_epp',
    englishQuery: 'auto darkening welding helmet welding mask safety',
    aliases: ['careta de soldar', 'careta fotosensible', 'mascara de soldar', 'welding helmet', 'careta electronica'],
    keywordsBilingual: ['welding helmet', 'auto darkening', 'careta soldar', 'arc welding', 'shade din', 'mig tig'],
    technicalRole: 'Protección ocular y facial integral contra radiación ultravioleta/infrarroja y arco eléctrico con oscurecimiento DIN 9-13 en 1/25,000 s',
    safetyRule: 'Verificar el estado de las baterías de litio y ajustar el potenciómetro de sombra según el amperaje del proceso SMAW/GMAW',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['mecanica_soldadura', 'electricidad_energia'],
    svgKey: 'gafas_seguridad',
  },
  {
    id: 'esmeriladora_angular',
    name: 'Esmeriladora Angular Portátil de 4 1/2 pulg',
    category: 'herramienta_taller',
    englishQuery: 'angle grinder metal grinding cutting power tool workshop',
    aliases: ['esmeriladora', 'esmeriladora angular', 'amoladora', 'pulidora angular', 'angle grinder', 'esmeril'],
    keywordsBilingual: ['angle grinder', 'esmeriladora', 'grinding disc', 'abrasive', 'rpm metal cutting'],
    technicalRole: 'Desbaste de cordones de soldadura, biselado de placas y corte abrasivo de perfiles metálicos y tubería',
    safetyRule: 'NUNCA operar sin la guarda protectora de acero en posición y utilizar careta facial completa sobre las gafas de seguridad',
    normaNOM: 'NOM-004-STPS-1999',
    familias: ['mecanica_soldadura', 'electricidad_energia'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'llave_perico_ajustable',
    name: 'Llave Ajustable de Acero Forjado (Perico)',
    category: 'herramienta_taller',
    englishQuery: 'adjustable wrench crescent wrench steel mechanical tool',
    aliases: ['perico', 'llave perico', 'llave ajustable', 'crescent wrench', 'llave perica'],
    keywordsBilingual: ['adjustable wrench', 'crescent wrench', 'llave ajustable', 'perico', 'jaw bolt tightening'],
    technicalRole: 'Sujeción y apriete de tuercas y tornillos de medidas diversas mediante tornillo sin fin de apertura variable',
    safetyRule: 'Aplicar la fuerza girando hacia el lado de la mordaza fija, nunca hacia la mordaza móvil para no vencer el tornillo sin fin',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['mecanica_soldadura', 'electricidad_energia', 'agropecuaria'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'nivel_torpedo_magnetico',
    name: 'Nivel Torpedo de Burbuja con Base Magnética',
    category: 'instrumento_medicion',
    englishQuery: 'torpedo level magnetic spirit level plumbing electrical',
    aliases: ['nivel torpedo', 'nivel de gota', 'nivel de burbuja', 'nivel magnetico', 'torpedo level'],
    keywordsBilingual: ['torpedo level', 'spirit level', 'nivel burbuja', 'plumb', 'horizontal level', 'magnetic level'],
    technicalRole: 'Comprobación rápida de nivelación horizontal, vertical (plomada) y a 45° en canalizaciones y estructuras metálicas',
    safetyRule: 'Limpiar la base ranurada en V con imanes de tierras raras para evitar lecturas falsas por virutas metálicas adheridas',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['mecanica_soldadura', 'electricidad_energia', 'diseno_grafico'],
    svgKey: 'vernier',
  },
  {
    id: 'extractor_rodamientos_tres_patas',
    name: 'Extractor Mecánico de Rodamientos de 3 Patas',
    category: 'herramienta_taller',
    englishQuery: 'three jaw bearing puller mechanical gear puller workshop',
    aliases: ['extractor de rodamientos', 'extractor de poleas', 'extractor de tres patas', 'bearing puller', 'extractor mecanico'],
    keywordsBilingual: ['bearing puller', 'gear puller', 'extractor rodamientos', 'three jaw', 'shaft removal'],
    technicalRole: 'Desmontaje axial no destructivo de baleros, engranajes y poleas ajustados a presión sobre flechas de motores',
    safetyRule: 'Centrar la punta cónica del tornillo extractor en el orificio central de la flecha para evitar que las patas se zafen bajo carga',
    normaNOM: 'NOM-004-STPS-1999',
    familias: ['mecanica_soldadura', 'electricidad_energia'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'arco_segueta_bimetalica',
    name: 'Arco para Segueta con Hoja Bimetálica de 12 pulg',
    category: 'herramienta_taller',
    englishQuery: 'hacksaw frame metal cutting bi metal blade workshop',
    aliases: ['arco de segueta', 'segueta', 'sierra para metales', 'hacksaw', 'arco para metales'],
    keywordsBilingual: ['hacksaw', 'segueta', 'metal cutting', 'bimetal blade', 'tpi teeth'],
    technicalRole: 'Corte manual de tubos, perfiles y varillas metálicas seleccionando el dentado adecuado (18, 24 o 32 dientes por pulgada)',
    safetyRule: 'Instalar la hoja con los dientes orientados hacia adelante y tensar la mariposa hasta que emita un sonido agudo al pulsar',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['mecanica_soldadura', 'electricidad_energia'],
    svgKey: 'herramienta_generica',
  },
];
