/**
 * salud.ts — Familia Tecnológica: Salud, Clínica y Asistencia Médica
 * SIGPDA-EMS · SEMS Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const SALUD_CATALOG: CatalogItem[] = [
  {
    id: 'baumanometro_aneroide',
    name: 'Esfigmomanómetro Aneroide (Baumanómetro)',
    category: 'salud_clinica',
    englishQuery: 'aneroid sphygmomanometer blood pressure cuff clinical',
    aliases: ['baumanometro', 'esfigmomanometro', 'tensiometro', 'baumanómetro', 'esfigmomanómetro', 'tensiómetro', 'medidor de presion'],
    keywordsBilingual: ['sphygmomanometer', 'blood pressure', 'baumanometro', 'cuff', 'systolic', 'diastolic'],
    technicalRole: 'Medición de la presión arterial sistólica y diastólica en mm de mercurio (mmHg) por método auscultatorio',
    safetyRule: 'Colocar el brazalete 2.5 cm arriba del pliegue del codo con la cámara inflable sobre la arteria braquial desinflada totalmente',
    normaNOM: 'NOM-030-SSA2-2009',
    familias: ['salud'],
    svgKey: 'multimetro',
  },
  {
    id: 'estetoscopio_doble_campana',
    name: 'Estetoscopio Clínico de Doble Campana',
    category: 'salud_clinica',
    englishQuery: 'clinical stethoscope medical dual head',
    aliases: ['estetoscopio', 'fonendoscopio', 'estetoscopio clinico', 'fonendo', 'stethoscope'],
    keywordsBilingual: ['stethoscope', 'estetoscopio', 'auscultation', 'heart sounds', 'breath sounds', 'chest piece'],
    technicalRole: 'Auscultación acústica de ruidos cardíacos, murmullos pulmonares y sonidos de Korotkoff para signos vitales',
    safetyRule: 'Desinfectar las olivas y el diafragma con alcohol etílico al 70% entre paciente y paciente',
    normaNOM: 'NOM-030-SSA2-2009',
    familias: ['salud'],
    svgKey: 'multimetro',
  },
  {
    id: 'glucometro_capilar',
    name: 'Glucómetro Capilar Digital',
    category: 'salud_clinica',
    englishQuery: 'blood glucose meter glucometer diabetes testing',
    aliases: ['glucometro', 'glucómetro', 'medidor de glucosa', 'glucometer', 'tiras de glucosa'],
    keywordsBilingual: ['glucometer', 'glucose meter', 'glucometro', 'glycemia', 'capillary blood', 'mg/dl'],
    technicalRole: 'Determinación cuantitativa rápida de glucosa en sangre capilar en mg/dL para monitoreo metabólico',
    safetyRule: 'Desechar inmediatamente la lanceta usada en el contenedor rígido rojo de punzocortantes RPBI sin reencapuchar',
    normaNOM: 'NOM-087-SEMARNAT-SSA1-2002',
    familias: ['salud'],
    svgKey: 'multimetro',
  },
  {
    id: 'oximetro_pulso',
    name: 'Oxímetro de Pulso de Dedo (Pulsioxímetro)',
    category: 'salud_clinica',
    englishQuery: 'pulse oximeter finger oxygen saturation monitor spo2',
    aliases: ['oximetro', 'oxímetro', 'pulsioximetro', 'pulsioxímetro', 'oximetro de pulso', 'pulse oximeter'],
    keywordsBilingual: ['oximeter', 'pulse oximeter', 'oximetro', 'spo2', 'oxygen saturation', 'pulse rate'],
    technicalRole: 'Medición no invasiva de la saturación de oxígeno en hemoglobina arterial (%SpO2) y frecuencia del pulso cardíaco',
    safetyRule: 'Retirar esmalte de uñas o sudor del dedo del paciente para evitar lecturas erróneas por dispersión de luz infrarroja',
    normaNOM: 'NOM-030-SSA2-2009',
    familias: ['salud'],
    svgKey: 'multimetro',
  },
  {
    id: 'termometro_infrarrojo_clinico',
    name: 'Termómetro Clínico Digital Infrarrojo',
    category: 'salud_clinica',
    englishQuery: 'clinical infrared forehead thermometer medical temperature',
    aliases: ['termometro clinico', 'termómetro clínico', 'termometro infrarrojo', 'termometro digital'],
    keywordsBilingual: ['thermometer', 'infrared thermometer', 'termometro', 'body temperature', 'forehead'],
    technicalRole: 'Medición sin contacto o de contacto rápido de la temperatura corporal central en grados Celsius (°C)',
    safetyRule: 'Mantener la distancia recomendada por el fabricante (3 a 5 cm de la frente o sien) libre de cabello y sudor',
    normaNOM: 'NOM-008-SCFI-2002',
    familias: ['salud'],
    svgKey: 'multimetro',
  },
  {
    id: 'martillo_reflejos',
    name: 'Martillo de Reflejos Neurológicos (Taylor)',
    category: 'salud_clinica',
    englishQuery: 'reflex hammer neurological reflex test taylor hammer',
    aliases: ['martillo de reflejos', 'martillo neurologico', 'martillo taylor', 'reflex hammer'],
    keywordsBilingual: ['reflex hammer', 'martillo reflejos', 'neurology', 'patellar reflex', 'tendon'],
    technicalRole: 'Evaluación de los arcos reflejos osteotendinosos profundos (rotuliano, bicipital, aquíleo) y sistema neuromuscular',
    safetyRule: 'Aplicar un golpe seco, percutiendo sobre el tendón relajado del paciente sin generar dolor excesivo',
    normaNOM: 'NOM-004-SSA3-2012',
    familias: ['salud'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'contenedor_rpbi_rojo',
    name: 'Contenedor Rígido para Punzocortantes RPBI',
    category: 'seguridad_epp',
    englishQuery: 'sharps container biohazard medical waste disposal',
    aliases: ['contenedor rpbi', 'bote rpbi', 'bote de punzocortantes', 'recipiente rpbi', 'sharps container'],
    keywordsBilingual: ['sharps container', 'biohazard', 'rpbi', 'punzocortantes', 'waste disposal'],
    technicalRole: 'Depósito seguro y definitivo de agujas, lancetas, bisturís y hojas punzocortantes con material biológico-infeccioso',
    safetyRule: 'Llenar únicamente hasta el 80% de su capacidad nominal y cerrar la tapa con traba irreversible para su recolección',
    normaNOM: 'NOM-087-SEMARNAT-SSA1-2002',
    familias: ['salud', 'biotecnologia'],
    svgKey: 'matraz_erlenmeyer',
  },
];
