/**
 * tics-ciberseguridad.ts — Familia Tecnológica: TICs, Ciberseguridad y Redes
 * SIGPDA-EMS · DBEPA Puebla MCCEMS 2026-2027
 */

import type { CatalogItem } from './types';

export const TICS_CIBERSEGURIDAD_CATALOG: CatalogItem[] = [
  {
    id: 'probador_cable_red_tester',
    name: 'Probador de Cable de Red UTP (Cable Tester RJ45)',
    category: 'instrumento_medicion',
    englishQuery: 'network cable tester rj45 ethernet lan tester',
    aliases: ['probador de cable', 'cable tester', 'tester de red', 'probador rj45', 'comprobador de cable'],
    keywordsBilingual: ['cable tester', 'network tester', 'rj45 tester', 'ethernet tester', 'pinout', 'continuity lan'],
    technicalRole: 'Verificación secuencial de continuidad pin a pin (1 al 8) y detección de pares cruzados o abiertos en cables T568A/B',
    safetyRule: 'No conectar nunca a líneas telefónicas activas ni a switches PoE que suministren 48V sin protección del tester',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['tics_ciberseguridad', 'electronica_mecatronica'],
    svgKey: 'probador_red',
  },
  {
    id: 'crimpadora_rj45',
    name: 'Pinza Crimpadora / Ponchadora Modular RJ45',
    category: 'herramienta_taller',
    englishQuery: 'rj45 crimping tool network crimper ethernet cable',
    aliases: ['crimpadora', 'ponchadora rj45', 'pinza ponchadora', 'crimping tool', 'crimpadora de red'],
    keywordsBilingual: ['crimping tool', 'crimper', 'crimpadora', 'rj45', 'modular plug', 'ethernet cable'],
    technicalRole: 'Fijación por compresión mecánica de los pines dorados del conector RJ45 en los 8 conductores del cable UTP',
    safetyRule: 'Verificar la posición de los colores de la norma T568B antes de prensar el trinquete hasta el tope final',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['tics_ciberseguridad'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'herramienta_impacto_punchdown',
    name: 'Herramienta de Impacto (Punch Down Tool 110/Krone)',
    category: 'herramienta_taller',
    englishQuery: 'punch down tool network keystone patch panel 110',
    aliases: ['herramienta de impacto', 'punch down', 'ponchadora de impacto', 'herramienta 110', 'punchdown tool'],
    keywordsBilingual: ['punch down', 'impact tool', 'keystone jack', 'patch panel', '110 block'],
    technicalRole: 'Inserción y corte automático del exceso de alambre en bloques de conexión IDC de jacks keystone y patch panels',
    safetyRule: 'Orientar la cuchilla con filo ("CUT") hacia la parte exterior del conector jack para no cortar el conductor de datos',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['tics_ciberseguridad'],
    svgKey: 'herramienta_generica',
  },
  {
    id: 'generador_tonos_sonda',
    name: 'Generador de Tonos y Sonda Rastreadora (Tóner)',
    category: 'instrumento_medicion',
    englishQuery: 'network tone generator probe cable tracker tracer',
    aliases: ['generador de tonos', 'sonda inductiva', 'rastreador de cables', 'toner y sonda', 'chicharra de red'],
    keywordsBilingual: ['tone generator', 'cable tracer', 'inductive probe', 'toner', 'wire tracking'],
    technicalRole: 'Identificación y rastreo inductivo de cables en manojos dentro de canalizaciones o racks sin pelar conductores',
    safetyRule: 'Desconectar el equipo de red activo antes de inyectar el tono analógico de alta frecuencia en la línea',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['tics_ciberseguridad', 'electricidad_energia'],
    svgKey: 'multimetro',
  },
  {
    id: 'patch_panel_rack',
    name: 'Panel de Parcheo (Patch Panel Cat 6) y Rack',
    category: 'tecnologia_computo',
    englishQuery: 'network patch panel 24 port rack mount server',
    aliases: ['patch panel', 'panel de parcheo', 'rack de telecomunicaciones', 'distribuidor de red'],
    keywordsBilingual: ['patch panel', 'rack', 'network cabinet', 'cat6', 'keystone ports'],
    technicalRole: 'Terminación centralizada y ordenamiento del cableado estructurado horizontal que enlaza hacia el switch de red',
    safetyRule: 'Asegurar conexión de tierra física al chasis del rack de telecomunicaciones (menos de 5 Ω de resistencia)',
    normaNOM: 'NOM-001-SEDE-2012',
    familias: ['tics_ciberseguridad'],
    svgKey: 'osciloscopio',
  },
  {
    id: 'destornilladores_precision_ti',
    name: 'Juego de Destornilladores de Precisión Magnéticos',
    category: 'herramienta_taller',
    englishQuery: 'precision screwdriver set electronics computer repair',
    aliases: ['destornilladores de precision', 'desarmadores de precision', 'juego de desarmadores', 'kit torx', 'precision screwdrivers'],
    keywordsBilingual: ['precision screwdriver', 'screwdriver set', 'desarmadores', 'torx', 'phillips', 'electronics repair'],
    technicalRole: 'Apertura y montaje seguro de chasis de computadoras portátiles, servidores y dispositivos móviles sin barrer tornillos',
    safetyRule: 'Utilizar la punta magnetizada del tamaño exacto (PH000, T5, P2) y aplicar presión axial firme y perpendicular',
    normaNOM: 'NOM-017-STPS-2008',
    familias: ['tics_ciberseguridad', 'electronica_mecatronica'],
    svgKey: 'cautin',
  },
  {
    id: 'tester_fuente_poder_atx',
    name: 'Probador Digital de Fuentes de Poder ATX con LCD',
    category: 'instrumento_medicion',
    englishQuery: 'atx power supply tester digital lcd computer repair',
    aliases: ['tester de fuente', 'probador atx', 'probador de fuente de poder', 'atx tester', 'power supply tester'],
    keywordsBilingual: ['power supply tester', 'atx tester', 'probador atx', 'voltage rails', 'pg delay', '12v rail'],
    technicalRole: 'Diagnóstico rápido de voltajes (+3.3V, +5V, +12V, -12V, +5VSB) y tiempo de retardo Power Good (PG) en fuentes de PC',
    safetyRule: 'No abrir la carcasa metálica de la fuente ATX conectada; sus condensadores internos retienen voltajes letales de más de 300V',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['tics_ciberseguridad'],
    svgKey: 'multimetro',
  },
  {
    id: 'lector_codigo_barras_qr',
    name: 'Lector Óptico de Código de Barras y QR Láser',
    category: 'tecnologia_computo',
    englishQuery: 'barcode scanner qr code reader usb handheld laser',
    aliases: ['lector de codigo de barras', 'escaner de codigo de barras', 'lector qr', 'barcode scanner', 'pistola de codigo de barras'],
    keywordsBilingual: ['barcode scanner', 'qr reader', 'lector codigo barras', 'laser scanner', 'pos inventory'],
    technicalRole: 'Captura e ingreso automatizado de identificadores para inventarios, logística de almacén y sistemas de punto de venta',
    safetyRule: 'No apuntar el haz láser directamente a los ojos de personas para evitar deslumbramiento o daño retiniano (Láser Clase 2)',
    normaNOM: 'NOM-001-SCFI-2018',
    familias: ['tics_ciberseguridad', 'servicios_turismo'],
    svgKey: 'multimetro',
  },
];
