import https from 'https';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, '../src/lib/visual-engine/fonts');

const FONTS = [
  {
    url: 'https://github.com/google/fonts/raw/main/ofl/lato/Lato-Regular.ttf',
    varName: 'latoRegularB64',
    file: 'lato-regular.ts',
    label: 'Lato Regular',
  },
  {
    url: 'https://github.com/google/fonts/raw/main/ofl/lato/Lato-Bold.ttf',
    varName: 'latoBoldB64',
    file: 'lato-bold.ts',
    label: 'Lato Bold',
  },
  {
    url: 'https://raw.githubusercontent.com/JulietaUla/Montserrat/master/fonts/ttf/Montserrat-Bold.ttf',
    varName: 'montserratBoldB64',
    file: 'montserrat-bold.ts',
    label: 'Montserrat Bold',
  },
];

function download(url: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const follow = (u: string, redirects = 0) => {
      if (redirects > 5) return reject(new Error('Too many redirects'));
      https.get(u, { headers: { 'User-Agent': 'node' } }, (res) => {
        if (res.statusCode && res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return follow(res.headers.location, redirects + 1);
        }
        if (res.statusCode !== 200) return reject(new Error('HTTP ' + res.statusCode + ' for ' + u));
        const chunks: Buffer[] = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve(Buffer.concat(chunks)));
        res.on('error', reject);
      }).on('error', reject);
    };
    follow(url);
  });
}

async function main() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  for (const font of FONTS) {
    process.stdout.write('Descargando ' + font.label + '... ');
    const buf = await download(font.url);
    const kb = Math.round(buf.length / 1024);
    const b64 = buf.toString('base64');
    const ts = '// Auto-generated by generate_font_data.ts — DO NOT EDIT\n// ' + font.label + ' (' + kb + ' KB)\nexport const ' + font.varName + ' = "' + b64 + '";\n';
    const outPath = path.join(OUT_DIR, font.file);
    fs.writeFileSync(outPath, ts, 'utf8');
    console.log('OK (' + kb + ' KB) -> ' + font.file);
  }
  console.log('Fuentes listas en', OUT_DIR);
}

main().catch((e) => { console.error('ERROR:', e.message); process.exit(1); });